### ISSUE TITLE
Compatibility issues with the latest Discord update

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#101]
With the latest Discord update on June 30th, I have noticed these 2 visual bugs:

**A permanent scrollbar on the server list**
![image](https://user-images.githubusercontent.com/24306400/86150798-def5ce80-bacb-11ea-8f12-55164ce0e401.png)

**A strange light gray background on the member list that makes texts less contrasty**
![image](https://user-images.githubusercontent.com/24306400/86150886-fdf46080-bacb-11ea-9751-3f0195050397.png)

**Comment by CapnKitten** [comment]
Issue is fixed and now live, thanks.
