### ISSUE TITLE
Issue: Friends almost completely hidden

### ISSUE THREAD

**Issue by ESploitDEVS** [CapnKitten/Material-Discord#102]
![image](https://user-images.githubusercontent.com/62471562/86414093-034ed800-bc91-11ea-8abf-752734dad5be.png)

**Comment by CapnKitten** [comment]
Already noticed this, and is fixed. Just waiting to put it live, thanks.

**Comment by ESploitDEVS** [comment]
Np

**Comment by ESploitDEVS** [comment]
Btw does it auto update? @CapnKitten

**Comment by CapnKitten** [comment]
It should auto update after reloading your Discord client.

**Comment by ESploitDEVS** [comment]
K
