### ISSUE TITLE
ReadAllNotificationsButton visual issue.

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#103]
Oh hayo, got a problem with your theme and ReadAllNotificationsButton by DevilBro. In previous version button was looking much better. Now it's looking like this 
![изображение](https://user-images.githubusercontent.com/67780510/86447079-79991c00-bd1d-11ea-80bd-b0f861ab03f0.png)
Can you fix this please?

**Comment by CapnKitten** [comment]
Got it fixed, just gonna wait until a few more things are done before putting it live, thanks.
