### ISSUE TITLE
[BUG] Voice Channel Buttons Off Center

### ISSUE THREAD

**Issue by ESploitDEVS** [CapnKitten/Material-Discord#104]
![BUG](https://user-images.githubusercontent.com/62471562/86533843-f228e580-bea1-11ea-9f5a-081ecceb7123.png)

**Comment by CapnKitten** [comment]
Sorry for the delay, but I'm not able to reproduce this issue. Are you using any other themes/plugins that may interfere with it?

**Comment by CapnKitten** [comment]
Was able to experience it, so it'll be fixed in the next update.
