### ISSUE TITLE
Material icons problem

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#105]
Oh hello again. Got a problem when using Material discord in different language than English. In my sample - russian. 
Is it possible to get material icons in all languages?
![изображение](https://user-images.githubusercontent.com/67780510/86760053-9c913c00-c04d-11ea-9418-de18e9a87125.png)

**Comment by CapnKitten** [comment]
Didn't realize it when I was changing the icons, but it relies on the tooltips content to change the icon. I'll see about doing it another way. Sorry for the inconvenience.

**Comment by CapnKitten** [comment]
Update is live.
