### ISSUE TITLE
Message boxes looking weird

### ISSUE THREAD

**Issue by mxrixs** [CapnKitten/Material-Discord#106]
I basically use the newest version ( [this](https://betterdiscord.net/ghdl/?url=https://raw.githubusercontent.com/CapnKitten/Material-Discord/master/Material-Discord.theme.css) ) but the "speech bubbles" look completely off. Any help appreciated
[this is how they look](https://imgur.com/LjSvrW4)

**Comment by CapnKitten** [comment]
Do you have any plugins/themes that may interfere with it? If not, what chat font scaling and zoom level settings do you have set?

**Comment by mxrixs** [comment]
I don't have any Plugins/themes on, 
Appearance Settings are:
Theme: `Dark`
Massage Display: `Compact`
Chat Font size: `14`
Space between Message groups: `0`
Zoom level: `80`
ty for any help!

**Comment by CapnKitten** [comment]
Sweet, thanks for the extra info. There was a spacing issue when adjusting the font size with compact messages. That appears to be the only thing causing the problem, which will be fixed in the next update. Thanks.
