### ISSUE TITLE
Spotify Controls by DevilBro compatibility issue

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#107]
Howdy. Another problem got there, when using your theme with Spotify Controls plugin. Media buttons got no icons. Can you fix this please?
![изображение](https://user-images.githubusercontent.com/67780510/88214525-01aa7b80-cc63-11ea-800f-cb49f2e76bb2.png)

**Comment by CapnKitten** [comment]
I'll take a look at it as soon as I can, thanks.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the fix is now live.
