### ISSUE TITLE
Missing CSS color property on "Watch" button

### ISSUE THREAD

**Issue by jaaneh** [CapnKitten/Material-Discord#108]
When opening a user profile of someone that is live, the "Watch" button color is not set/applied correctly.

**Current**
![](https://i.imgur.com/5AGLyzR.png)

**Expected** 
![](https://i.imgur.com/n7CDUWo.png)

**Comment by CapnKitten** [comment]
I'll get that fixed as soon as I can, thanks.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the fix is now live.
