### ISSUE TITLE
Save/cancel buttons conflicting positioning with emoji selector

### ISSUE THREAD

**Issue by jaaneh** [CapnKitten/Material-Discord#109]
This theme adds a save and cancel button when editing already sent messages, and they are overlaying and conflicting with the emoji selector added by Discord. Maybe reposition these next to the emoji selector button.

Discord message without the Theme enabled
![](https://jaany.xyz/i/v5pqk.png)

Discord message with the Theme enabled
![](https://jaany.xyz/i/z0ojy.png)

**Comment by jaaneh** [comment]
Instead of opening another issue, I'll also add to this one: The new skeleton loading Discord introduced has a lighter color which doesn't look good with this theme. Would be great to support this as well. 👍 

Current
![](https://jaany.xyz/i/uer2h.png)

**Comment by CapnKitten** [comment]
Sorry for the delay, I'll get those fixed as soon as I can. Thanks.

**Comment by CapnKitten** [comment]
Issue is fixed in v2.3.3.3.
