### ISSUE TITLE
[REQUEST] Theming for BetterFormattingRedux & Fix for GoogleTranslateOption plugins

### ISSUE THREAD

**Issue by ScarletWolf275** [CapnKitten/Material-Discord#11]
Here's what the BetterFormattingRedux plugin looks like right now
<img width="733" alt="image" src="https://user-images.githubusercontent.com/19330439/41756802-1c968422-75e7-11e8-85a7-c2758db5c19e.png">
It's unthemed, would be nice if that can be done, even if it's a custom css and not in the theme by default

And, The Google Translate plugin is just messed up because of the resizing of the emoji button
<img width="736" alt="image" src="https://user-images.githubusercontent.com/19330439/41756836-3ddf5ad2-75e7-11e8-8db3-69b96fcce1bb.png">
Would be nice if it can be made it's own button like the emoji picker (the emoji picker's button is a square instead of just clicking on the emoji itself)
<img width="83" alt="image" src="https://user-images.githubusercontent.com/19330439/41756861-6398c740-75e7-11e8-9bd7-23d220db0652.png">
Here I was just hovering below the button and it still detected it, meaning the button I think is a square. Would be great if the same could be done to the translate button

**Comment by CapnKitten** [comment]
Button placement for the google translate button is better, and the BetterFormattingRedux is styled with the latest update, thank you.
