### ISSUE TITLE
Fix guild invites settings

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#110]
![2020-08-25 22_29_19-#general-en - Discord](https://user-images.githubusercontent.com/21284089/91224581-9b61be80-e722-11ea-8fc0-4ea97a39465b.png)

Thanks

**Comment by CapnKitten** [comment]
I'll give it fixed as soon as I can, thanks.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the update is live in v2.3.3.4.
