### ISSUE TITLE
Changing Font to avoid Legal Problems

### ISSUE THREAD

**Issue by Avxnt** [CapnKitten/Material-Discord#111]
To keep with the Material theme, I suggest switching to (preferably) [Roboto](https://fonts.google.com/specimen/Roboto), [Open Sans](https://fonts.google.com/specimen/Open+Sans), or [Noto Sans JP](https://fonts.google.com/specimen/Noto+Sans+JP) as all of them have an open license for use.

Using Product Sans is not allowed as per [Google's terms](https://fonts.google.com/license/productsans), and could result in bad stuff.

Plus, Roboto is more visually appealing, and has support for multiple characters/glyphs from different languages

**Comment by CapnKitten** [comment]
I had previously used Roboto in the theme, and eventually switched to Product Sans because I find it more visually pleasing. You can change it if you'd like in the custom CSS part of BetterDiscord though.

```css
* {
	font-family: 'FONT_NAME', sans-serif !important;
}
```
