### ISSUE TITLE
Scaling & Misalignment Issue

### ISSUE THREAD

**Issue by FennisOT** [CapnKitten/Material-Discord#112]
The line where the username and date/time is above a message becomes misaligned when chat font scaling is less than 16px. Example picture is using 14px. This also follows for uploading files and deleting files. Picture file preview is misaligned regardless of font size.
![Untitled](https://user-images.githubusercontent.com/14151917/92334341-e5b83900-f05a-11ea-9d5d-bc44daa7bb62.png)

![Untitled](https://user-images.githubusercontent.com/14151917/92334511-a7237e00-f05c-11ea-962f-ebebe68b1799.png)

![Untitled2](https://user-images.githubusercontent.com/14151917/92334514-ab4f9b80-f05c-11ea-9703-cfa53e95377b.png)

**Comment by CapnKitten** [comment]
Got this fixed with v2.3.3.5, thanks.
