### ISSUE TITLE
The discord lock icon is used for locked but visible voice channels

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#113]
Instead of the material icon, the discord icon is used
![image](https://user-images.githubusercontent.com/24306400/93827582-869c1c00-fc37-11ea-9816-102d3a1d203d.png)

**Comment by CapnKitten** [comment]
I'm not sure what permissions were set to display that icon, but I'm unable to reproduce it by setting the view permission to visable.

![8Bg5Eq](https://user-images.githubusercontent.com/4013216/93838572-1782ef80-fc58-11ea-93a0-d9f8de458e40.png)

**Comment by Jnss98b** [comment]
![image](https://user-images.githubusercontent.com/24306400/97819652-ed214a80-1c77-11eb-8949-291c7c88b032.png)

**Comment by Jnss98b** [comment]
It fixed itself in one of thee recent updates for me
