### ISSUE TITLE
Emojis and text misaligned when setting a custom status

### ISSUE THREAD

**Issue by MrJabberwock** [CapnKitten/Material-Discord#115]
Emojis and text appear misaligned when setting a custom status.

![image](https://user-images.githubusercontent.com/17773362/94821412-2c355500-03c7-11eb-8c83-9cfba4ed0aba.png)
![image](https://user-images.githubusercontent.com/17773362/94821098-d496e980-03c6-11eb-94a7-829dd6a69300.png)

**Comment by CapnKitten** [comment]
Got it fixed and will be in the next update, thanks.
