### ISSUE TITLE
Color changing help

### ISSUE THREAD

**Issue by Nexxol1** [CapnKitten/Material-Discord#116]
How do i change the color of this? 
![Discord_Z7XVbUCanW](https://user-images.githubusercontent.com/68960034/94987058-6cc5d780-055b-11eb-89e7-5546b6748ed3.png)
i cant find anywhere that says how to change it on the css

**Comment by CapnKitten** [comment]
That would be my bad. For some reason, I set the background color to `--input-color`, but I've changed it to `--popout-alt` in v2.3.3.7, thanks.
