### ISSUE TITLE
Read all button

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#117]
Hello there. Problems again. Guilds icons overlap read all button. Can you fix this please?
![изображение](https://user-images.githubusercontent.com/67780510/97730780-fa560200-1adc-11eb-9801-03ecb8fc8c45.png)

**Comment by CapnKitten** [comment]
I'll get it fixed as soon as I can, thanks.

**Comment by CapnKitten** [comment]
Got it fixed; update will live shortly.

**Comment by CapnKitten** [comment]
Update is live.
