### ISSUE TITLE
Server notification icon missing

### ISSUE THREAD

**Issue by jaaneh** [CapnKitten/Material-Discord#119]
After some recent update, the small icon that shows left of server icons in servers you have notifications in, is gone.

Expected ![](https://jaany.xyz/i/otpzk.png)

Current ![](https://jaany.xyz/i/3l6n7.png)

**Comment by Jnss98b** [comment]
I have the same issue on Windows 10 20H2

**Comment by BobbyWibowo** [comment]
+1

**Comment by CapnKitten** [comment]
It appears that the method I used for detecting unread messages is gone from BBD. I'll revert it to vanilla Discord until I can get a fix out because the unread notification is really annoying to deal with.

**Comment by CapnKitten** [comment]
Fix is live.

**Comment by Jnss98b** [comment]
The fix hasn't worked for me for some reason. Do I need to reinstall the theme?

**Comment by CapnKitten** [comment]
Shouldn't need to. Try fully restarting your discord app. If that doesn't work, then the easiest and quickest option is redownloading the theme.
