### ISSUE TITLE
Guild selector issue

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#121]
Hello again. Got this problem. Can you fix this?
![изображение](https://user-images.githubusercontent.com/67780510/98462765-39601380-21bf-11eb-8034-639d08b43fbc.png)

**Comment by CapnKitten** [comment]
I'm not sure what you're referring to, sorry.

**Comment by WellDonyEddy** [comment]
![изображение](https://user-images.githubusercontent.com/67780510/98462938-7c6eb680-21c0-11eb-958f-6e9d7f47fbce.png)
Servers and home button now got default selector and default notification counter.

**Comment by CapnKitten** [comment]
The method I used relied on specific BetterDiscord class names, and they're currently gone for some reason. So for the time being, I reverted the notification dots to vanilla Discord so they would actually work (they were blank prior to v2.3.3.9 that I pushed live the other day).
