### ISSUE TITLE
Weird scrollbar placement

### ISSUE THREAD

**Issue by seriaati** [CapnKitten/Material-Discord#122]
![image](https://user-images.githubusercontent.com/61446626/98490705-46d3d700-226d-11eb-9f0a-a1311dc87259.png)
In the ctrl+k menu.

**Comment by CapnKitten** [comment]
I'll get it fixed, thanks.

**Comment by seriaati** [comment]
:D

**Comment by CapnKitten** [comment]
Update is live.
