### ISSUE TITLE
Channel selection not working as intended.

### ISSUE THREAD

**Issue by seriaati** [CapnKitten/Material-Discord#123]
![image](https://user-images.githubusercontent.com/61446626/98894799-93731880-24e0-11eb-8bd3-b69da4816708.png)
As you can see the left bar is in the original discord color and it is not the same as the one shown in the preview.

**Comment by seriaati** [comment]
This issue seems to be happening in all betterdiscord themes, sorry.

**Comment by CapnKitten** [comment]
Discord updated, and I'll get it fixed. Thanks.
