### ISSUE TITLE
The new discord update seems to be messing around with betterdiscord

### ISSUE THREAD

**Issue by seriaati** [CapnKitten/Material-Discord#124]
![image](https://user-images.githubusercontent.com/61446626/98894898-ccab8880-24e0-11eb-8f5e-a893850dd95a.png)
The chat bubbles seem to be looking different?

**Comment by CapnKitten** [comment]
Nothing wrong with them, I updated them a few months ago with an add-on theme to enable the older message bubbles. The older messages can be downloaded [here](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CapnKitten/BetterDiscord/master/Themes/Material-Discord/css/Material-Discord_addon-messages.theme.css).
