### ISSUE TITLE
Channels list no longer themed as of today

### ISSUE THREAD

**Issue by sjain882** [CapnKitten/Material-Discord#125]
![image](https://user-images.githubusercontent.com/43217178/98935976-3b3a1780-24dc-11eb-81d6-44d4312590af.png)

Tried removing all my custom CSS and reinstalling the theme, to no avail

**Comment by CapnKitten** [comment]
Discord updated it. Just pushed the update live. Restarting your discord app should get you the update.

**Comment by sjain882** [comment]
Thank you so much! <3
