### ISSUE TITLE
sending arrow weird placement

### ISSUE THREAD

**Issue by seriaati** [CapnKitten/Material-Discord#126]
I'm sorry to bother you again
Thanks for fixing the previous issues I reported, your theme is amazing!
But as you can see:
![image](https://user-images.githubusercontent.com/61446626/99016235-a09c1000-2591-11eb-98ef-0d85dea90bda.png)
When the user edits a message, the sending arrow appears in a weird position.
It only occurs when the messages are all in a big bubble
![image](https://user-images.githubusercontent.com/61446626/99016378-f83a7b80-2591-11eb-9d0b-11d660867093.png)
And the first line of message has correct position of arrow
![image](https://user-images.githubusercontent.com/61446626/99016481-2d46ce00-2592-11eb-9763-3f789a098316.png)
But the ones below are messed up like the image shown at the start.
It is a minor bug though

**Comment by CapnKitten** [comment]
Got it fixed and will be in the next update, thanks.

**Comment by CapnKitten** [comment]
Update is live.
