### ISSUE TITLE
Incompatibility with new "reply" feature

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#127]
## Message history

| Base | Material |
| ---- | -------- |
| ![2020-11-18 21_51_29-#discord - Discord](https://user-images.githubusercontent.com/21284089/99589289-10742580-29ec-11eb-8610-dad7de494f0e.png) | ![2020-11-18 21_50_58-#discord - Discord](https://user-images.githubusercontent.com/21284089/99589302-1538d980-29ec-11eb-983c-0f734ee99cef.png) |

## Message text input

| Base | Material |
| ---- | -------- |
| ![2020-11-18 22_20_01-Microsoft Store](https://user-images.githubusercontent.com/21284089/99589490-592bde80-29ec-11eb-80ea-1bf6148926ef.png) | ![2020-11-18 22_20_24-Microsoft Store](https://user-images.githubusercontent.com/21284089/99589508-5e892900-29ec-11eb-8e21-716489bc3591.png)

## Message attachment input

| Base | Material |
| ---- | -------- |
| ![2020-11-18 22_22_36-#discord - Discord](https://user-images.githubusercontent.com/21284089/99589818-cc355500-29ec-11eb-91bb-31c9b76127f4.png) | ![2020-11-18 22_23_06-#discord - Discord](https://user-images.githubusercontent.com/21284089/99589834-d0617280-29ec-11eb-93a5-c004c07e811e.png) |

If you don't have access to the feature, install the [Discord Experiments](https://raw.githubusercontent.com/Inve1951/BetterDiscordStuff/master/plugins/discordexperiments.plugin.js) plugin, then click on the newly added `Experiments` tab in settings and finally select `Treatment 1` on `Inline replies` :

![2020-11-18 22_25_52-#discord - Discord](https://user-images.githubusercontent.com/21284089/99590194-554c8c00-29ed-11eb-8568-643297930526.png)

Thanks ! :)

**Comment by CapnKitten** [comment]
Fix is live.

**Comment by KaKi87** [comment]
Thanks ! However, it still seems to be destyled in message attachment input.
