### ISSUE TITLE
Channel video icons

### ISSUE THREAD

**Issue by onrdrsy** [CapnKitten/Material-Discord#128]
The small icon is not visible next to people who turn on their cameras.

Normal Discord
![Discord_cop5AZNZiH](https://user-images.githubusercontent.com/20243362/100345206-09a07080-2ff3-11eb-8dc7-a792c4dca66f.png)

Material Discord
![Discord_XRj9npluma](https://user-images.githubusercontent.com/20243362/100345211-0ad19d80-2ff3-11eb-8df7-4d9da02787ea.png)

**Comment by CapnKitten** [comment]
Sorry for the delay. I'll get it fixed, thanks.

**Comment by onrdrsy** [comment]
> Sorry for the delay. I'll get it fixed, thanks.
It's okay. I liked this theme and can wait for it to be better. :D

There seems to be a problem with the video player interface as well.

Full Screen:
![Discord_Bz8zOBQ91D](https://user-images.githubusercontent.com/20243362/101189351-fda65580-3667-11eb-9acc-0686f1270aac.png)
Chat:
![Discord_C9BKCzx3O6](https://user-images.githubusercontent.com/20243362/101189355-fed78280-3667-11eb-97b6-88f5a66e5c9c.png)

**Comment by CapnKitten** [comment]
Got both of those issues fixed and will be in the next update.
