### ISSUE TITLE
Discord tips not themed

### ISSUE THREAD

**Issue by ScarletWolf275** [CapnKitten/Material-Discord#13]
Title. 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/19330439/41779670-35105452-763b-11e8-834f-594bbd47e7d5.png">
This happens with the Invite one too

**Comment by ScarletWolf275** [comment]
I think they're all `.channelNotice-1-XFjC` classes, don't know tho

**Comment by CapnKitten** [comment]
Unable to get those to show up, but I'll get them updated the next time I see them.
