### ISSUE TITLE
Message addon problem

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#130]
Hello there! Problems again. When i use your material discord theme with message addon in compact mode, i see weird artifacts in user messages.
![изображение](https://user-images.githubusercontent.com/67780510/101241223-e1082d00-36fc-11eb-8dd7-43654dad818b.png)

**Comment by CapnKitten** [comment]
Update for the messages addon theme is live. You might have to redownload the addon theme file again.
