### ISSUE TITLE
Certain character combinations automatically being converted into unicode emojis

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#131]
Hi!

I couldn't help but notice that this theme changes certain character combinations, such as ":)", to their respective unicode counterparts. In this example, ":)" would get changed to "`☺`". In my opinion this is rather intrusive and this should be disabled or there should be at least an option to turn this off. 

I have wondered quite long what causes this obnoxious behaviour until i finally found out today..

**Comment by CapnKitten** [comment]
This theme doesn't do that, it's an option in your "Text & Images" settings. I'm rather curious as to what your troubleshooting methods were that lead you to believe that it was the theme.


![a7Bg56J](https://user-images.githubusercontent.com/4013216/103405291-996e9880-4b24-11eb-9751-f4a7f9dd2bf3.png)

**Comment by Maximilian1271** [comment]
Hello again

I am aware of this option, however this is turned off on my end and it is definitely not responsible for this.
However, i might need to apologize regardless:

I have not troubleshot this using inspector at all.. Only after posting this issue i for some reason had the idea. That said however, i am still not 100% sure if this issue appears only on my setup or if it only doesn't affect your setup @CapnKitten 

You see, after investigating this further, i have concluded the "product sans" font is at fault for doing this. Disabling `font-family: 'Product Sans';` will fix the issue. However, it could be that my theme is using a locally installed version of product sans (which does exist).

I am going to investigate.. Sorry again for the premature bug report though!

**Comment by Maximilian1271** [comment]
Yeah sorry that was completely on my part :( 

It was the locally installed "Product Sans" font that did it.. Sorry AGAIN.. I should have really tested this before writing a ticket..

**Comment by CapnKitten** [comment]
It's all good. Having an issue like this is way better than the numerous people trying to update the source code of any of the BBD themes I've made because they changed a variable to customize their install of said theme.
