### ISSUE TITLE
Sidebar icons beta

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#132]
Hello. I using better discord beta. And BD settings got no icons. Can you fix this?
![изображение](https://user-images.githubusercontent.com/67780510/104331995-67800d80-54f8-11eb-9456-dbe584b411d1.png)

**Comment by CapnKitten** [comment]
I actually don't target the PTB or canary because they get changed so often, sorry. But I do have canary downloaded and the icons are present there.

**Comment by CapnKitten** [comment]
Fixed with v3.0.0.
