### ISSUE TITLE
Plugins  issue

### ISSUE THREAD

**Issue by WellDonyEddy** [CapnKitten/Material-Discord#135]
Hello there. Got problems with old title bar and read all addons.
They are not properly themed. Can you fix this?
![изображение](https://user-images.githubusercontent.com/67780510/106876449-6188e100-66e0-11eb-9b83-5046046f7e9b.png)

**Comment by CapnKitten** [comment]
Old Title Bar is styled as it should be. I'll have the Read All Notifications added though.
