### ISSUE TITLE
Light Theme Issues 

### ISSUE THREAD

**Issue by SimplyNoni** [CapnKitten/Material-Discord#137]
Settings Icons are white
![image](https://user-images.githubusercontent.com/54287388/106970965-f230e280-671b-11eb-8382-df8b21fec519.png)

Description of rich presences is white 
![image](https://user-images.githubusercontent.com/54287388/106971542-21941f00-671d-11eb-9ce2-52837627fb9b.png)

Hovering over search options looks weird
![image](https://user-images.githubusercontent.com/54287388/106971752-8f404b00-671d-11eb-9f1a-2987f25b8e6e.png)

White text in game activity settings
![image](https://user-images.githubusercontent.com/54287388/106972012-0544b200-671e-11eb-9ccb-81aa00645870.png)

**Comment by CapnKitten** [comment]
I'll have all of these fixed in the next update.
