### ISSUE TITLE
Custom CSS editor character width does not match cursor character spacing

### ISSUE THREAD

**Issue by vmurray1** [CapnKitten/Material-Discord#138]
When editing custom CSS rules with the theme enabled the editor cursor thinks that characters are wider than they appear on screen, thus editing becomes very difficult because you can't tell what character you're currently modifying.
![image](https://user-images.githubusercontent.com/13809828/106987360-41d2d680-673b-11eb-8ef3-5207e947bd72.png)
The editor window in the screenshot above contains no spacing characters of any kind.

**Comment by CapnKitten** [comment]
Pushed and update that'll fix this. Restarting your Discord client should get it for you.
