### ISSUE TITLE
Server Welcome Screen Editor Issue 

### ISSUE THREAD

**Issue by SimplyNoni** [CapnKitten/Material-Discord#139]
When adding a new channel to the welcome screen, the emoji picker is inside of the text box and you can't click on it 
![image](https://user-images.githubusercontent.com/54287388/107109825-508bbd00-6811-11eb-8450-df0e885336a9.png)

**Comment by CapnKitten** [comment]
Just pushed an update to the source code that'll fix this. Restarting your Discord client should get the update.
