### ISSUE TITLE
After latest Discord update folder area has themeing issues

### ISSUE THREAD

**Issue by sjain882** [CapnKitten/Material-Discord#141]
the --server-color variable doesn't affect the server sidebar anymore. The set color shows on the background of the read all button here, but it doesnt apply to the actual background of the server side bar list.

![image](https://user-images.githubusercontent.com/43217178/112758846-42277980-8fe8-11eb-88dc-50dc0ebd06e3.png)

Also i think theres some issues with folders not theming properly, like the closed background, icons, etc, was wondering if you noticed any issues

Also, calls seem to have theme issues or mostly unthemed:

![image](https://user-images.githubusercontent.com/43217178/112759198-e362ff80-8fe9-11eb-85ca-83ddf137734d.png)

![image](https://user-images.githubusercontent.com/43217178/112759203-e8c04a00-8fe9-11eb-88e9-b604d38ff200.png)

doesnt respect accent color ^

popout screen share gets cut off in the bottom left:

![image](https://user-images.githubusercontent.com/43217178/112759241-0b526300-8fea-11eb-8a48-e47a36429f85.png)

And is mostly unthemed:

![image](https://user-images.githubusercontent.com/43217178/112759272-27ee9b00-8fea-11eb-9c59-d1d34780f681.png)

![image](https://user-images.githubusercontent.com/43217178/112759275-2b822200-8fea-11eb-9da0-36eb9f6c3436.png)

![image](https://user-images.githubusercontent.com/43217178/112759281-3046d600-8fea-11eb-92ec-19939524e3c5.png)

![image](https://user-images.githubusercontent.com/43217178/112759301-418fe280-8fea-11eb-9f98-0eb07047ccd8.png)

thanks for the great theme!

**Comment by CapnKitten** [comment]
The server list and folders have been fixed, and I'll take a look at the rest of the theming issues. Thanks.
