### ISSUE TITLE
Theme not working for me since 6th April.

### ISSUE THREAD

**Issue by ABongoCat** [CapnKitten/Material-Discord#142]
Opened Discord today and saw that every other plugin and theme would load, but not the Material Discord Theme. I already uninstalled Bandage Discord, Repaired, Downloaded Material Discord v3.0.3, but the Theme would not load.
![image](https://user-images.githubusercontent.com/45139479/113690039-4845e600-96cb-11eb-8d8f-0aeebffe92ac.png)

**Comment by CapnKitten** [comment]
Take the import url and paste it in your browser to see if it loads for you there.

**Comment by sjain882** [comment]
It works for me. You should be using the new BetterDiscord Beta, not Banadaged.
