### ISSUE TITLE
In homepage friends menu is a different color

### ISSUE THREAD

**Issue by GiaSen** [CapnKitten/Material-Discord#144]
![immagine](https://user-images.githubusercontent.com/30241358/118099369-6c38cd80-b3d5-11eb-8dc6-f5cfce9f5c77.png)

I've tried to disable/renable or close and repoen, I have no idea how it randomly happened.
Stable 84785 (fe5e237)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

**Comment by CapnKitten** [comment]
Issue has been fixed, restart your client to get the update.

**Comment by GiaSen** [comment]
yes, thank you
