### ISSUE TITLE
Managing Roles in a Server with Theme on doesn't work

### ISSUE THREAD

**Issue by ABongoCat** [CapnKitten/Material-Discord#146]
Appeared on my PC today. 18th May 2021

With Material:
![image](https://user-images.githubusercontent.com/45139479/118666175-3dff2780-b7f3-11eb-8c1a-12d57cfdd2d8.png)

Without:
![image](https://user-images.githubusercontent.com/45139479/118666265-52432480-b7f3-11eb-8587-9213bf43a367.png)

The CSS Version I tried to change to:

```
/**
 * @name Material_Discord
 * @version 3.0.3
 * @description A theme based on Google's Material Design
 * @author CapnKitten
 * 
 * @website http://github.com/CapnKitten
 * @source https://github.com/CapnKitten/BetterDiscord/blob/master/Themes/Material-Discord/css/source.css
 * @donate https://paypal.me/capnkitten
 * @invite jzJkA6Z
 */

@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/source.css);

:root {
	--accent-color: #577be2;
	--accent-rgb: 94,122,199;
	--accent-text-color: #fff;
	--accent-button-action: #fff; /*	-	*/

	--message-radius: 19px;
	--message-padding: 8px 12px;
	--message-padding-alt: 4px 12px 8px 12px; /*	-	*/

	--card-radius: 5px;
	--card-radius-big: 10px;
}
```

**Comment by CapnKitten** [comment]
This has been fixed. Reload your discord client to get the update.

**Comment by ABongoCat** [comment]
> This has been fixed. Reload your discord client to get the update.

Yup it's working again. Thank you! I really like this theme.
