### ISSUE TITLE
Minor incompatability with UnreadBadgesRedux plugin

### ISSUE THREAD

**Issue by ramenchef** [CapnKitten/Material-Discord#147]
Using this theme with UnreadBadgesRedux creates a minor bug in the UI.
![image](https://user-images.githubusercontent.com/1252949/119296102-2ec21480-bc0d-11eb-92c9-daa98f05af31.png)
Unread messages show up in the bottom right corner with a red colored badge, which overlaps where the mention badge, also red, shows up.

**Comment by CapnKitten** [comment]
I'll get support for UnreadBadgesRedux added to the theme.

**Comment by CapnKitten** [comment]
Sorry for the delay, but this has been fixed. Restart your Discord to get the update.
