### ISSUE TITLE
About Me + Roles (and Activities list) broken in user pop out

### ISSUE THREAD

**Issue by JunctionNinja** [CapnKitten/Material-Discord#148]
![image](https://user-images.githubusercontent.com/62995181/123133932-2c3f1e80-d448-11eb-80c6-684b038b22ce.png)

Don't have an old SS but it should all be equally sized and the roles have a weird black border behind them.

**Comment by CapnKitten** [comment]
This has been fixed, just restart your Discord to get the update. Thanks.
