### ISSUE TITLE
Inconsistent theming with the new threads feature

### ISSUE THREAD

**Issue by Benji7103** [CapnKitten/Material-Discord#150]
the new threads update leads to threads being displayed in the standard discord UI style and position, therefore they intersect with materialdicords UI modifications, I was able to fix this using this Custom-CSS in betterediscord:
```
.container-3hZ-gs{
    margin-left: 57px !important;
    margin-bottom: 8px !important;
    border-radius: 8px !important;
    padding: 9px !important
}
.cozy-3raOZG.hasThread-2k82W0:after{
    border-bottom-left-radius: 12px !important;
    bottom: 43px !important;
    top: 55px !important;
}
```

**Comment by CapnKitten** [comment]
This has been fixed. Restart your Discord client to get the update.
