### ISSUE TITLE
Can't select text in message I've been pinged in

### ISSUE THREAD

**Issue by MGThePro** [CapnKitten/Material-Discord#152]
Can't reproduce similar behaviour with other themes or no theme set at all. Happening on both Discord Stable and Discord PTB using BetterDiscord. When hovering the mouse above such a message the cursor doesn't change to the regular line thing it usually does with text. When I'm starting to select text from a different message, and continue moving to the message with the ping still gets selected. And I just noticed that there is a very small (like 1-2 pixel tall) area right above the text where selecting still works, just above the blue marking.

**Comment by CapnKitten** [comment]
This has been fixed.
