### ISSUE TITLE
[BUG] Name misaligned on Compact Mode

### ISSUE THREAD

**Issue by BLANK-TH** [CapnKitten/Material-Discord#154]
When you use this theme in compact mode, the front of a user's name sticks out of the textarea.

Image for example:  
![](https://blank.life-is-pa.in/59ZGGJkdJ.png)

Zoomed in a bit with a line to show where the box is:
![](https://blank.life-is-pa.in/59ZHd04Yt.png)

**Comment by CapnKitten** [comment]
Mind telling me your chat font scaling and zoom levels?

**Comment by BLANK-TH** [comment]
Chat font scaling is at 16px, and zoom level is 80%

**Comment by CapnKitten** [comment]
I can't reproduce it. Have you fully restarted your Discord client lately to make sure you're using the latest version of the theme? If so, are you using any plugins that would alter the messages?

**Comment by BLANK-TH** [comment]
I have fully restarted my Discord client and also have the most recent (downloaded yesterday) version of the theme. As for plugins that could alter the message, maybe? I do have a fair number of plugins however they *shouldn't* affect the theme. The ones that could affect the theme are:

- Radial Status Theme
- Staff Tag

However with both of them disabled, the issue still persists. When I'm free later today, I'll try and disable all the plugins then re-enable them one by one to narrow down the issue.

**Comment by CapnKitten** [comment]
It's the 24 hour timestamps doing it. I'll get it fixed.

**Comment by BLANK-TH** [comment]
Really? Issue still happened when I had it disabled. Maybe I didn't refresh it properly after disabling that. Either way, thanks for fixing it.
