### ISSUE TITLE
Profile pictures not showing in chat

### ISSUE THREAD

**Issue by risa401** [CapnKitten/Material-Discord#16]
Messages (Cozy Mode) don't have the profile picture next to them.
Started happening from nowhere. Yesterday (no updates on anything from what I know) it was working just fine.

Installed newest update of this theme too, didn't help.

![image](https://user-images.githubusercontent.com/11839880/43676127-f9273876-97ea-11e8-8746-128cccf1452f.png)

**Comment by CapnKitten** [comment]
There was an update, and I'll get it fixed as soon as possible.
