### ISSUE TITLE
for some reason not working on discord canary...

### ISSUE THREAD

**Issue by UltimateBoi** [CapnKitten/Material-Discord#161]

**Comment by CapnKitten** [comment]
Switch over to stable for now. The canary update broke pretty much every theme.

**Comment by UltimateBoi** [comment]
its fixed now with the XenoLib update I think.

**Comment by CapnKitten** [comment]
The canary update went to the stable release, so I updated the theme.

**Comment by UltimateBoi** [comment]
oh ok cool
