### ISSUE TITLE
New discord update seems to be broke the theme

### ISSUE THREAD

**Issue by Taiyou06** [CapnKitten/Material-Discord#162]
[Material-Discord.theme.txt](https://github.com/CapnKitten/Material-Discord/files/7846309/Material-Discord.theme.txt)

i've tried both clean config and my old config both doesn't work.

![image](https://user-images.githubusercontent.com/77050201/148940044-7baa36ad-6b9c-4e8e-9c85-8ba54eef75e8.png)

discord logo should change according to my accent color

**Comment by CapnKitten** [comment]
Use the updated theme file with the new accent variables. It has been switched over to strictly HSL instead of hex and RGB.
