### ISSUE TITLE
Theme interfering with "BetterFormattingRedux" plugin by "Zerebos" under certain conditions

### ISSUE THREAD

**Issue by m-scha1337** [CapnKitten/Material-Discord#163]
Hey!
This is a very minor issue i just noticed. I'm not even sure whether to post this observation here or over at the plugin repo. But somebody on the official BetterDiscord server suggested i should post it here, so here goes:

The Plugin "[BetterFormattingRedux](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/BetterFormattingRedux)" adds a small "∧" symbol above the message text-box which opens advanced message formatting options on-hover.

Under normal circumstances, the theme and the plugin play nicely together. However: If a channel is declared a slowmode channel, either the text "Slowmode is enabled. ⏱" or the remaining time until a message can be sent again will overlap the previously mentioned "∧" symbol.

Now i know this is an edge case. As said: I didn't even know if to post this here or at the plugin developers repo. Therefore i must stress that i **do not want to imply any sort of urgency** whatsoever. 
But it would be massively appreciated if a workaround could be implemented at some point in the future :)

Attached is a screenshot depicting the issue "in action":
![98c62692adc9540380b48678590b0f3a137fb14a](https://user-images.githubusercontent.com/1573345/150511479-c3ac3706-f71c-4401-a74f-3769369a9cfa.png)

**Comment by m-scha1337** [comment]
One thing i forgot to mention:
This is without the recent, large discord update. I am still on discord version "Stable 111534", which should be the one prior to the update that is breaking so many things right now.
Upon hearing there is a large, BetterDiscord breaking update inbound, i disabled auto updates temporarily.

The theme however is up-to-date (v.3.0.3), as is the plugin (v2.3.12)

**Comment by CapnKitten** [comment]
Stable is on the same version an canary, which is 111534, so you've already gotten the update. But I'll make the plugin easier to use.

**Comment by m-scha1337** [comment]
> Stable is on the same version an canary, which is 111534, so you've already gotten the update. But I'll make the plugin easier to use.

Huh.. Very peculiar because i haven't had any issues with any plugins so far on this version..

But either way: Thank you very much for your ongoing work and dedication to this theme :) It is by far my most favourite one!

**Comment by CapnKitten** [comment]
This has been fixed. Restart your Discord client to get the update.
