### ISSUE TITLE
Context Menu Issues

### ISSUE THREAD

**Issue by PersianDevs** [CapnKitten/Material-Discord#166]
I have problems when i right click on the user to open context menu

https://user-images.githubusercontent.com/98149620/154923338-064c5487-aa80-43b5-b32b-f1e2b92ca0c9.mp4

Using Theme version 3.0.4
Using latest version of Better Discord

I disabled the BDFPD Plugin and Image Utilities and its now fixed idk if its theme's issue or not
I think the problem would occur when something new is added to context menu:
![image](https://user-images.githubusercontent.com/98149620/154923963-acf4a5b7-751d-4891-bc8f-3f88e502dd51.png)

**Comment by CapnKitten** [comment]
ImageUtilities is the culprit. For some reason it resets the right click menu. In the case of Material Discord, since it has a right click animation, it's more noticeable.
