### ISSUE TITLE
Problems with switching status

### ISSUE THREAD

**Issue by imTheSupremeOne** [CapnKitten/Material-Discord#17]
You can't do it)

I think there is problem with your animation and timings, because panel will disappear after you click on status(and it wont be changed), but if you hold mouse button for some time at status it sometimes will work.

**Comment by ThatRichard** [comment]
Not happening for me.

**Comment by CapnKitten** [comment]
Made it so the animation is just a fade, instead of sliding down for the time being. Should fix the issue for you. The update is live.
