### ISSUE TITLE
send button looks weirdly placed and isn't coloured by material you addon

### ISSUE THREAD

**Issue by nanopone** [CapnKitten/Material-Discord#170]
![image](https://user-images.githubusercontent.com/49787675/166615006-7ee1e9e8-f17a-4535-a8e7-2a2fd4305874.png)

**Comment by CapnKitten** [comment]
This has been updated. Restart your discord to see the changes.

**Comment by nanopone** [comment]
now the icon is outlined even though i have the filled icons addon
![QkmwZ9Bj0l](https://user-images.githubusercontent.com/49787675/166685355-6d305d4d-7e64-4cd2-85ec-f23ee8265ef4.png)

**Comment by CapnKitten** [comment]
Add-on theme has been updated.
