### ISSUE TITLE
Mini Profile info colors background white in dark mode?

### ISSUE THREAD

**Issue by CSeriestechhero** [CapnKitten/Material-Discord#174]
I've been using Material_Discord for a few days and really enjoy the layout and style of it, but whenever I show the small user info panel [dark mode enabled], the background color is near white, while text is also white in dark mode. It makes it really hard to read.
![image](https://user-images.githubusercontent.com/64616029/178382131-914686bc-f395-4983-9b80-1f483dd82266.png)
![image](https://user-images.githubusercontent.com/64616029/178382382-61bc2a86-3e0c-404a-a618-7d9eeceadf15.png)
The specific OS is **elementary OS 6.1 jolnir (x86-64)**.
And in case my DE might be interfering with how it is rendering, I'm using Cinnamon version 4.4.8.
Discord's hardware acceleration IS enabled.

**Comment by CapnKitten** [comment]
That's the new profile popout that Discord appears to be rolling out. I'll get it styled once it's fully released.

**Comment by CSeriestechhero** [comment]
Oh sweet, thx.
