### ISSUE TITLE
Volume slider on audio files getting clipped by content container

### ISSUE THREAD

**Issue by aniketjs** [CapnKitten/Material-Discord#178]
#### Description
The audio volume slider on audio files gets clipped by the parent element(?).
Or there is something wrong with the hierarchy of the z-indexes perhaps(?).
#### Screenshots
![](https://media.giphy.com/media/tU7RI66kzPJbO0kpKk/giphy.gif)

#### Files
https://github.com/CapnKitten/BetterDiscord/blob/master/Themes/Material-Discord/src/messages/_attachment.scss

#### To Reproduce
- Upload an audio file to a channel or message box.
- Pull up the audio slider control to the top.

**Comment by CapnKitten** [comment]
Side effect from something unrelated. I'll get it fixed.
