### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by sirzento** [CapnKitten/Material-Discord#179]
Idk why but the background color is darker than displayed on the preview pictures. The background color is the same color as the background at the channel select.:

My discord:

![](https://i.imgur.com/ofRi4Sq.png)

Preview:

![](https://user-images.githubusercontent.com/4013216/151684066-302585e8-4266-4c76-8eb2-af4042ba40ce.png)
_____
Also the three buttons when in a call are still blue colored. When adding "!important" to the css property of the button they will get the right color: 

**Currently:**

![](https://i.imgur.com/CLpX53X.png)

After the fix:

![](https://i.imgur.com/jHxVTc2.png)

![](https://i.imgur.com/bASUkfz.png)

______

The two buttons on the left side are also blue:

![](https://i.imgur.com/yRTKuoX.png)

But when disabling a rule it will get the right color (it will get --background-primary):

![](https://i.imgur.com/QWS8eg5.png)

![](https://i.imgur.com/OR2U939.png)

**Comment by CapnKitten** [comment]
The chat background color was updated, and a disclaimer is above the preview images.
![image](https://user-images.githubusercontent.com/4013216/206410978-78dede36-ffc1-4a92-a008-dd7639017ab7.png)

Most buttons use the accent color set by `--accent-hue`, `--accent-saturation`, and `--accent-lightness`. Text color is also controlled by `--accent-text-color`. The buttons you mentioned are styled as they should be for the theme.

You can view all of the variables [here](https://github.com/CapnKitten/Material-Discord#variables).

**Comment by sirzento** [comment]
Oh okey. I thought those buttons are way to bright so I did thought they ment to be dark.
Do you maybe have the old values for the colors of the chat background?
