### ISSUE TITLE
Incompatibility with ImageGallery plugin

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#18]
Hello,

There is a glitch using the BetterDiscord plugin ImageGallery : https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ImageGallery

![2018-08-26 22_52_04-](https://user-images.githubusercontent.com/21284089/44632870-b908bb80-a982-11e8-9a45-c48e937ae76e.png)

Could you fix it please ?

Thanks !!! :)

**Comment by CapnKitten** [comment]
Of course, I'll have a fix out as soon as possible.

**Comment by KaKi87** [comment]
Thanks !

**Comment by CapnKitten** [comment]
Culprit was .inner-1JeGVc having a relative positioning so I could move the open externally button. Simple fix, and is live.

**Comment by KaKi87** [comment]
Very good, thank you !
