### ISSUE TITLE
some incompatible styling in plugin settings

### ISSUE THREAD

**Issue by ghoomy** [CapnKitten/Material-Discord#183]
![image](https://user-images.githubusercontent.com/35694451/213888971-9a765c8c-b8e5-473c-929f-71c3255fe6bf.png)

**Comment by CapnKitten** [comment]
You're gonna have to tell me which plugin that is.

**Comment by ghoomy** [comment]
ChatAliases

**Comment by CapnKitten** [comment]
This will be fixed whenever I push the next update live.
