### ISSUE TITLE
Home, New Server and Discover icons have no hover styling

### ISSUE THREAD

**Issue by ghoomy** [CapnKitten/Material-Discord#185]

**Comment by KTibow** [comment]
discover and home have hover styling for me
![image](https://user-images.githubusercontent.com/10727862/214175265-91cf4ebe-18de-44b9-9f50-f0e2d3a5994a.png)
![image](https://user-images.githubusercontent.com/10727862/214175298-f24e95e7-f55f-48ff-b242-bdd5c35be0e9.png)

**Comment by ghoomy** [comment]
![image](https://user-images.githubusercontent.com/35694451/214179933-69294b88-a4e9-4380-b017-e3e605a5afce.png)
![image](https://user-images.githubusercontent.com/35694451/214179992-8d907853-f877-4964-80a8-7ec2147492f3.png)
![image](https://user-images.githubusercontent.com/35694451/214179881-7d9d809b-0c96-489e-8c23-7666febcba38.png)

**Comment by KTibow** [comment]
i see an indicator upon hover (given that you're not already focused on the page) for friends and discover

**Comment by KTibow** [comment]
note that this is mostly the same behavior as normal discord

**Comment by ghoomy** [comment]
Normally, the icon would get inverted.

**Comment by KTibow** [comment]
ah i think removing the border-radius changing was intentional

**Comment by CapnKitten** [comment]
I'll get a hover effect added.
