### ISSUE TITLE
Could be more accurate

### ISSUE THREAD

**Issue by KTibow** [CapnKitten/Material-Discord#186]
While I enjoy this theme it doesn't really encapsulate Material You/3. Take this switch for instance:
![image](https://user-images.githubusercontent.com/10727862/214176264-2df1857e-0048-42cc-bb64-f3984732dc59.png)
![image](https://user-images.githubusercontent.com/10727862/214176286-c637b4a8-51e7-463c-9fd9-55b93ccdfa31.png)
In reality a switch looks like this:
![image](https://user-images.githubusercontent.com/10727862/214176335-2b01a419-60ba-4320-bcfc-ffa85d4b3a4d.png)
For another example, in this theme a button is 36px high with 16px padding. In reality buttons are 40px high with 24px padding.
This theme has a different variable system than Material uses, and while that's annoying for getting the right colors, bringing this theme up to spec should still be possible.

**Comment by CapnKitten** [comment]
The theme isn't one to one of M3. It is based on it, but not entirely the same.

**Comment by KTibow** [comment]
right - material you lets you change colors, and i know this is just an inspired theme
would you be open to prs to change the styling?

**Comment by CapnKitten** [comment]
I can definitely look into it and play around with it. Certain areas are actually too small for the official M3 dimensions. For example, chips in the user pop out for the roles are smaller than what Google specifies due to them appearing toi large for the area.
