### ISSUE TITLE
Channel icons are misaligned

### ISSUE THREAD

**Issue by MGIsHeree** [CapnKitten/Material-Discord#192]
Channel icons seems to be misaligned. Also applies to voice channels as well.
![image](https://github.com/CapnKitten/Material-Discord/assets/51394649/bb423e33-5f1c-497b-8722-7e28753eee05)
![image](https://github.com/CapnKitten/Material-Discord/assets/51394649/de7446b1-41e1-4be7-aa95-862abf1430b7)

**Comment by CapnKitten** [comment]
Sorry for the delay. This has been fixed.
