### ISSUE TITLE
Reply message highlight is gone

### ISSUE THREAD

**Issue by 3kh0** [CapnKitten/Material-Discord#193]
Normal box without theme

![image](https://github.com/CapnKitten/Material-Discord/assets/58097612/56b89e7f-4e4f-4140-b977-f544e5879504)

Reply box without theme

![image](https://github.com/CapnKitten/Material-Discord/assets/58097612/4699279a-8467-498c-b4c0-2a35fba832d4)

Normal box with theme

![image](https://github.com/CapnKitten/Material-Discord/assets/58097612/dfe0e055-1d0d-4b16-8538-9cc55094fce2)

Reply box with theme

![image](https://github.com/CapnKitten/Material-Discord/assets/58097612/6b521cf8-a69a-4d87-bc99-c143c7b4e88c)

**Comment by kittenvr** [comment]
@CapnKitten

**Comment by CapnKitten** [comment]
This was already added to the theme.
