### ISSUE TITLE
what is this new look

### ISSUE THREAD

**Issue by AmEg11** [CapnKitten/Material-Discord#195]
colors stayed the same as the default discord theme... or is it just me?

**Comment by Koning-Chocolademelk** [comment]
Also having this issue.

**Comment by RobsonMi** [comment]
As far as I know it's the latest Discord that broke things. See BetterDiscord homepage warning:
![obraz](https://github.com/CapnKitten/Material-Discord/assets/15092964/bf03d114-27e3-4bac-8cb8-c0db6195ca3e)

**Comment by WebTheDev** [comment]
From what I've gathered, discord rewrote a lot of their build configuration including the css classes to improve performance. The theme just needs to be updated to reflect the new build configuration changes.

**Comment by CapnKitten** [comment]
Discord update broke all themes by change every class name. It will take some time to get everything updated, but I am working on it.

**Comment by CapnKitten** [comment]
This issue has been resolved.
