### ISSUE TITLE
Stream preview dissapeared

### ISSUE THREAD

**Issue by D0m1nu2** [CapnKitten/Material-Discord#198]
Whenever I tab out of the stream I'm watching it disappears instead of showing up in the corner of Discord like it normally should.
![image](https://github.com/CapnKitten/Material-Discord/assets/75164010/1f6489cd-fe4e-4df7-9f23-2aa16efa9a1c)
![image](https://github.com/CapnKitten/Material-Discord/assets/75164010/38f25292-ba31-482c-b22f-1777bb2b2f12)
I've tried removing all Vencord plugins, nothing changed, the only thing that fixed it was disabling this amazing theme sadly

**Comment by CapnKitten** [comment]
Fix is live.
