### ISSUE TITLE
Theme broken with newer versions of Discord PTB

### ISSUE THREAD

**Issue by MGThePro** [CapnKitten/Material-Discord#199]
Hello, unfortunately it seems like Discord broke the theme last night. With the theme enabled it now looks mostly like stock Discord with a few things broken like incorrect message spacing. As an example: 

![Screenshot_20240229_110651](https://github.com/CapnKitten/Material-Discord/assets/17652761/2ec78978-b7e4-4ae7-819e-a39eab06dfcf)

This is with ptb 269740 with vencord 8ccd731 on linux

**Comment by TailsFanLOL** [comment]
Literally just wanted to say this (on canary), refreshed the page and this appeared 😅

**Comment by TailsFanLOL** [comment]
![Before, @ 2024-02-24 21-53-10 UTC+2](https://github.com/CapnKitten/Material-Discord/assets/96183936/cc6b450f-cfff-4c51-88ab-8ce1c428b6b3)

![After, @ 2024-02-29 12-06-52 UTC+2](https://github.com/CapnKitten/Material-Discord/assets/96183936/ddbfdb0b-fe25-4fbe-9f9c-f6f27d35f567)

Here's the comparison of before and after. The user bar also appears broken. Hovering over messages shows their timestamps right on top of the message text.

My QuickCSS: ```css
@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/source.css);
@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/addons/icons/source.css);
@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/addons/custom-themes/source.css);

:root {
	--accent-hue: 224;
	--accent-saturation: 71%;
	--accent-lightness: 61%;
	--accent-text-color: #fff;
	--accent-button-action: #fff; /*	-	*/

	--avatar-radius: 50%; /*	-	*/

	--message-radius: 19px;
	--message-padding-top: 8px;
	--message-padding-side: 12px; /*	-	*/

	--media-radius: 19px; /*	-	*/

	--card-radius: 8px;
	--card-radius-big: 18px; /*	-	*/

	--popout-radius: 8px;
	--popout-radius-big: 18px;

    --app-font: "Roboto";
    --code-font: "MxPlus IBM VGA 9x16";

}
code {
    font-size: 16px !important;
}
```

**Comment by CapnKitten** [comment]
Switch to stable for now. The theme won't be updated for ptb or canary since they have updated class names and in doing so, would break the theme for stable.

**Comment by TailsFanLOL** [comment]
![Снимок экрана в 2024-02-29 15-18-27](https://github.com/CapnKitten/Material-Discord/assets/96183936/55c39428-f5b9-4b1e-9883-1c476f3b665a)
Update: this happened now

**Comment by CapnKitten** [comment]
You should stop using canary and PTB for the time being. They are broken, and will remain broken until stable gets updated because fixing those two would break stable.

**Comment by MGThePro** [comment]
Weirdly enough it..... works now, kind of?

The theme itself works but the colors are weirdly blue, here's a screenshot:
![Screenshot_20240305_095753](https://github.com/CapnKitten/Material-Discord/assets/17652761/0a4de0c8-fdad-42a8-a823-cc53cc188e67)

**Comment by TailsFanLOL** [comment]
For me it just started working again like 3 days ago but forgot to say here.
I don't know what's up with the colors, thought.

**Comment by AstudilloMarillo** [comment]
It is broken for me on stable atm. Been like that for I think 2(?) days.

**Comment by CapnKitten** [comment]
It was fixed the day of the discord update. You just needed to restart your discord.
