### ISSUE TITLE
"Hello, Anyone There?" Notification Off Center.

### ISSUE THREAD

**Issue by crazyian1000** [CapnKitten/Material-Discord#20]
Hello! Just a minor issue I came across, when being moved to an AFK channel automatically, it seems the "Okay" button is pushed to the right rather than centered. Thanks!

![capture](https://user-images.githubusercontent.com/25258572/45244873-8d54d200-b2ae-11e8-934c-ad7845281637.PNG)

**Comment by CapnKitten** [comment]
I'll get it fixed as soon as possible, thanks.

**Comment by CapnKitten** [comment]
Fix is live.
