### ISSUE TITLE
Add transparent background

### ISSUE THREAD

**Issue by BLACK4585** [CapnKitten/Material-Discord#200]
Hey, I really like your theme! The only thing I wish would exist is a transparent, blurry background. I tried to mix the right CSS in from https://github.com/mwittrien/BetterDiscordAddons/tree/master/Themes/BasicBackground and https://github.com/FeoreV/Themes/blob/e07d6bfc3ce663865ae650eb58b5901d8a8d1109/Discord/Release/FVUI.theme.css#L51, especially the MICA Version but I didn't manage to do it. 
Is this a possible thing?

**Comment by sorae42** [comment]
Enable Transparency in BetterDiscord Settings > Window Preferences and make changes to the CSS that it allows passthrough.

**Comment by BLACK4585** [comment]
Yes, I'm aware of the first point. But I don't know what needs to be done to enable it. That's why I opened this issue.

**Comment by CapnKitten** [comment]
Do what they said and change `--app-bg` to transparent.

**Comment by BLACK4585** [comment]
![grafik](https://github.com/CapnKitten/Material-Discord/assets/71935902/515fdf95-e7fe-4d3a-92fd-78d5a00ccf72)
This is the result in Vencord. Is this because of Vencord, an update by discord which broke sth or one of this addons?
![grafik](https://github.com/CapnKitten/Material-Discord/assets/71935902/b6edd829-4141-48cb-9eb9-925c71dcc6f7)

**Comment by sorae42** [comment]
Try doing this on BetterDiscord and see if it works.
