### ISSUE TITLE
Voice chat user limit

### ISSUE THREAD

**Issue by Jent1357** [CapnKitten/Material-Discord#203]
![Screenshot 2024-04-16 202138](https://github.com/CapnKitten/Material-Discord/assets/130794034/a546b78c-4c11-43e5-a6ff-dfe74851f545)
I'm not 100% sure if this comes from any incompatibility with any other plugin I have installed, or if this is just an error in the theme.

**Comment by CapnKitten** [comment]
Forgot a semicolon one a line when converting the old hex color codes to HSL. Fix is live.
