### ISSUE TITLE
Possibility to change to old theme? (v3.0.5)

### ISSUE THREAD

**Issue by tnguyen2601** [CapnKitten/Material-Discord#205]
I do like the darker theme more than this purple-esque color scheme. What is needed to revert to that?

**Comment by CapnKitten** [comment]
Material You is enabled by default on the theme, but it can be easily disabled. Find the theme file for your respective client mod below.

BetterDiscord:
`%appdata%\BetterDiscord\themes`

Vencord:
`%appdata%\Vencord\themes`

Then find this line of code in the theme file.
 ```css
/* Material You addon */
@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/addons/material-you/source.css);
```
Replace the @import line with the following line of code
```css
/* Material You addon */
/*@import url(https://capnkitten.github.io/BetterDiscord/Themes/Material-Discord/css/addons/material-you/source.css);*/
```
