### ISSUE TITLE
Add friend icons etc. not lining up with their frames when viewing profiles in servers

### ISSUE THREAD

**Issue by trdko** [CapnKitten/Material-Discord#206]
![Snímek obrazovky 2024-05-18 173920](https://github.com/CapnKitten/Material-Discord/assets/29510982/a850ea40-c0c6-462e-bf3a-c23894aa516d)

**Comment by CapnKitten** [comment]
It's the new simplified profile design. It's unfortunately not out for everyone, including myself, so I can't style it just yet.

**Comment by ImMALWARE** [comment]
> It's the new simplified profile design. It's unfortunately not out for everyone, including myself, so I can't style it just yet.

you can enable it via experiments. dont remember exact name, but NTTS made video about this

**Comment by CapnKitten** [comment]
I don't style experimental things because they almost always change before they're released and can take months.

**Comment by CapnKitten** [comment]
Forgot to update this issue, but this was fixed a few weeks ago when Discord fully released this change.
