### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by BoolmanO** [CapnKitten/Material-Discord#207]
Either I'm blind, or this doesn't really exist. How can I customize the color of this input?
![image](https://github.com/CapnKitten/Material-Discord/assets/96051241/0f179f10-07e2-4554-92a3-321e50d4970c)

Thanks for your work, the theme is great.

**Comment by CapnKitten** [comment]
That looks like the new simplified user profile feature that Discord is A/B testing. It'll be styled once it's fully released, which hopefully will be soon.

**Comment by CapnKitten** [comment]
Update is live.
