### ISSUE TITLE
So many things have broken

### ISSUE THREAD

**Issue by KTibow** [CapnKitten/Material-Discord#208]
1. Messages is padded too much, and has unthemed placeholders
2. Servers have lost the custom rounded styling
3. `@mentions` have lost their colors
4. User profiles have buttons with glitched text
5. Some buttons (eg Sort in members) have white on primary text instead of `on-primary` on primary text
6. More stuff that I can't recall

**Comment by CapnKitten** [comment]
I'm aware. Discord has pushed a number of updates lately. I'll get them fixed.

**Comment by CapnKitten** [comment]
Fixed.
