### ISSUE TITLE
Bot profile popouts are a bit buggy

### ISSUE THREAD

**Issue by s1nnohlakes** [CapnKitten/Material-Discord#213]
The bot profile popouts seem to be out of scope with the user profile popouts. It's also a bit buggy and doesn't expand throughout the whole profile unless hovered.

![image](https://github.com/user-attachments/assets/9e52fc2d-9384-44ac-86f5-13f7c96eb425)

**Comment by CapnKitten** [comment]
I pushed an update live. Restart your Discord app and let me know if you're still experiencing this issue.

**Comment by s1nnohlakes** [comment]
Issue still persists.

![image](https://github.com/user-attachments/assets/4384936a-0093-4ea6-be36-b2f45e3aaa14)

**Comment by CapnKitten** [comment]
Wait, I'm just now realizing that you're using the older style of profiles that Discord phased out. The image below shows the current style.

![image](https://github.com/user-attachments/assets/cec359e0-5424-461b-b9d4-b2253b81fd2c)

**Comment by s1nnohlakes** [comment]
Huh, strange. The issue seems to have disappeared all of a sudden. My Discord client, or account rather probably got into some weird test or experiment where the bot profiles were still using the old style. Or at the very least Discord fixed the inconsistency.

I'll keep the issue open for a while 'til I'm sure it's completely fixed.

![image](https://github.com/user-attachments/assets/041052b4-3da6-43c8-905f-4ccdf4e761cf)

**Comment by s1nnohlakes** [comment]
Issue fixed. Closing now.
