### ISSUE TITLE
Image / Video controls aren’t styled properly

### ISSUE THREAD

**Issue by s1nnohlakes** [CapnKitten/Material-Discord#217]
Image and video controls have been left out since about a week ago.

![image](https://github.com/user-attachments/assets/d12bf3c9-10e7-43c7-85f5-6196de448e25)
![image](https://github.com/user-attachments/assets/8b3a7b57-d927-4d0d-94be-0dd75607731c)
![image](https://github.com/user-attachments/assets/44fc0813-d00a-4cc3-87c7-ea506affb088)

**Comment by CapnKitten** [comment]
It's actually been a lot longer than that lol. Video controls have been unstyled for probably over a year at this point. I'll get them fixed.

**Comment by CapnKitten** [comment]
Fixed.
