### ISSUE TITLE
Emoji menu in upload modal

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#22]
![2018-10-02 15_26_14- humour - discord](https://user-images.githubusercontent.com/21284089/46351499-cdae3280-c657-11e8-8b81-2806d37d891c.png)

**Comment by CapnKitten** [comment]
I'm not able to reproduce that. Are you using any plugins that might effect it?

**Comment by KaKi87** [comment]
Well, I disabled all my plugins then restarted Discord, I still have the same problem.

Here are some screenshots.

Theme disabled :
![2018-10-15 09_28_34- admins-discussions - discord](https://user-images.githubusercontent.com/21284089/46936026-44d2c600-d05d-11e8-8599-29efd59e9bc9.png)

Theme enabled :
![2018-10-15 09_29_06- admins-discussions - discord](https://user-images.githubusercontent.com/21284089/46936030-48fee380-d05d-11e8-8fbb-0c3581e597ee.png)

Sorry for the late answer.

Thanks

**Comment by CapnKitten** [comment]
I've updated it, and it'll be live with the next update, thank you.
