### ISSUE TITLE
Accents w/ Custom Themes Issue

### ISSUE THREAD

**Issue by WebTheDev** [CapnKitten/Material-Discord#221]
Hi There!

I have both base material discord and the custom themes add-on installed. However, I'm getting some sections of Discord that are still in the native dark theme. Screenshots have been attached below:

![image](https://github.com/user-attachments/assets/eb0bcddc-299e-4a7c-b326-cc758cf95eaa)

![image](https://github.com/user-attachments/assets/ebd0b51c-2dde-46f5-8bef-9e7a067692ea)

**Comment by CapnKitten** [comment]
Fixes are live.
