### ISSUE TITLE
Suggestion: Make this a user theme on other sites!

### ISSUE THREAD

**Issue by elouangrimm** [CapnKitten/Material-Discord#222]
I absolutely love this theme. It is so much better than regular discord (I use it in Vencord web). I would love to have this same CSS theme be available for sites like Spotify, Github, Google, or Youtube. (Those are the main ones). This theme as a Spotify theme would be incredible! If you make a `.crx` extension that would just theme Spotify or Youtube or whatever by detecting the site and applying the material theme to it, that would be amazing. Thanks!

**Comment by CapnKitten** [comment]
It won't translate to other sites, as they use different layouts, classes, etc.. You'd have to pretty much rewrite the entire thing.
