### ISSUE TITLE
Text area patch 10/25/2024

### ISSUE THREAD

**Issue by Soveien** [CapnKitten/Material-Discord#223]
As of 10/25/2024 the text area variables have been changed. You can paste the code below into your theme.css file to patch it.

```
.scrollableContainer_bdf0de.themedBackground_bdf0de {
  background-color: var(--input-color) !important;
  border-radius: 22px;
}
.channelTextArea_a7d72e {
  background-color: rgba(0, 0, 0, 0) !important;
}
```

Before:
![before](https://github.com/user-attachments/assets/a4ab7bbc-2f40-43ba-864e-7e09e9728379)
After:
![After](https://github.com/user-attachments/assets/9fce31a5-e04b-40ae-859f-59347ee04c3b)

**Comment by CapnKitten** [comment]
Fix is in the source, but thank you for this.
