### ISSUE TITLE
GameActivityToggle plugin incompatability

### ISSUE THREAD

**Issue by StrandAlexander** [CapnKitten/Material-Discord#224]
![image](https://github.com/user-attachments/assets/e8af3c1a-4c8d-46be-8cd6-691b5eae8671)
![image](https://github.com/user-attachments/assets/881dc65f-7ee2-48db-803e-1452b723dab7)
Noted this error when toggling game activity in the "activity bar"
Worth mentioning that I'm using "material you" but it seems to be the base theme that's causing the SVG icon to get squished. Screenshot for base reference:
![image](https://github.com/user-attachments/assets/ebfef77d-198d-4b08-b0d8-b4f8e808afac)

**Comment by CapnKitten** [comment]
This is fixed, restart your Discord to get it the update.
