### ISSUE TITLE
theme don't look like the photos:c

### ISSUE THREAD

**Issue by Mapacheb** [CapnKitten/Material-Discord#226]
![image](https://github.com/user-attachments/assets/4d088def-9b2b-431f-a4e3-b18ad0e89528)
it's just me?

**Comment by s1nnohlakes** [comment]
Firstly; there is a notice in the README. 
![image](https://github.com/user-attachments/assets/ed08a437-4685-477b-ba6b-ad263267e336)
And second; the previews shown use the Material You addon for this theme, which you can [download or import separately](https://github.com/CapnKitten/BetterDiscord/tree/master/Themes/Material-Discord/css/addons/material-you).

**Comment by CapnKitten** [comment]
If you downloaded the theme file within the last 8 months, Material You is enabled by default. Like stated above, it looks like you're not using it, which can only be accomplished by manually removing the import url on the latest version or using an outdated theme version that required the theme addon. I'd suggest redownloading the theme to get the latest imports and easily customized variables.
