### ISSUE TITLE
Call not filling the whole area when in fullscreen

### ISSUE THREAD

**Issue by ItsGarek** [CapnKitten/Material-Discord#227]
To reproduce:

1. Use a 1440p display
2. Enter a conversation
3. Enable fullscreen mode
4. The conversation isn't filing the whole area

![Discord_JqjgpNR7i4](https://github.com/user-attachments/assets/af114133-4b8a-4459-881a-802996fb1b49)
![image](https://github.com/user-attachments/assets/ee9b082c-0676-4edd-a9eb-07d2eb489bdf)

_Avatars erased for privacy reasons_

**Comment by CapnKitten** [comment]
So lemme clarify some things to avoid any confusion on my part.

1. Join a voice chat with someone streaming.
2. Watch the stream.
3. Go full screen.

After doing that multiple times, I'm not able to recreate the issue you're having. It goes full screen with no issues.

**Comment by ItsGarek** [comment]
I am going to try this again later today
