### ISSUE TITLE
Slow mode and BetterFormattingRedux

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#23]
Hello,

![2018-10-09 09_42_36- blabla-detente-1 - discord](https://user-images.githubusercontent.com/21284089/46654059-16aa3d80-cba8-11e8-90e2-f332caf73859.png)

Since slowmode we can't use BetterFormating because the arrow button is behind the slowmode banner.

Thanks ! 😉

**Comment by CapnKitten** [comment]
Thanks for point that out. Got it fixed, and will be live in the next update.
