### ISSUE TITLE
Twitter video/gif embeds

### ISSUE THREAD

**Issue by slashiee** [CapnKitten/Material-Discord#24]
When trying to view a twitter video or gif, it'll ask if you want to go to the tweet's page instead
![2018-11-10_22-06-31](https://user-images.githubusercontent.com/15317421/48309741-f79b2480-e534-11e8-9bc6-0b3419edc7cb.png)
![2018-11-10_22-06-51](https://user-images.githubusercontent.com/15317421/48309744-f8cc5180-e534-11e8-9148-723939caecaf.png)

**Comment by CapnKitten** [comment]
I have this fixed and will be in the next update, thank you.
