### ISSUE TITLE
Settings switches look wrong

### ISSUE THREAD

**Issue by CherenTheCat** [CapnKitten/Material-Discord#25]
For some reason, after the most recent BandagedBD update, the switches in settings have looked incorrect.
![image](https://user-images.githubusercontent.com/18288725/48530462-6e9a2b00-e85d-11e8-8da2-cff886ac5fe2.png)
I have no idea if this is an issue only I'm having, or what, but turning the theme off makes them look right in the normal discord appearance, so I'm assuming there's an error with the theme.

**Comment by CapnKitten** [comment]
That's weird, because I reinstalled the latest BandagedBD and don't have the same results.
