### ISSUE TITLE
Bug with ServerFolders

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#27]
Hello,

We can't see the unread count using the [ServerFolders](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders) plugin :

![2018-12-13 15_57_38-](https://user-images.githubusercontent.com/21284089/49946950-5404b180-fef0-11e8-9ffd-9c107625fda1.png)

Could you show the unread count on right side or resize icons and/or column width ?

It would be also a bonus if you could make the folder open animation smoother.

Thanks ! ;)

**Comment by CapnKitten** [comment]
Fixed and an update will be pushed out shortly, thanks.

**Comment by KaKi87** [comment]
Well, thank you for your exceptional reactivity 😊
