### ISSUE TITLE
[Request] Make online statuses back at their place

### ISSUE THREAD

**Issue by imTheSupremeOne** [CapnKitten/Material-Discord#3]
I think its very unusual for me as well as for more other people, and also causing some bad looking exeptions when theme is used with some plugins:

with:
![image](https://user-images.githubusercontent.com/13508453/38955503-8f7f11c8-435d-11e8-88c9-e7c6f258ccda.png)

without:
![image](https://user-images.githubusercontent.com/13508453/38955541-a7cff850-435d-11e8-90ca-e5e269abcbeb.png)

**Comment by CapnKitten** [comment]
I can't control what plugins add, but what plugin(s) are talking about?

**Comment by imTheSupremeOne** [comment]
Server folder by mwitten: https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders

With material discord installed, plugin icon that show you how many servers in folder, is moved top, at the bottom of the next server, and its looks like the amount of notifications.

And for testings, I've also loaded this with another theme and everything also ok:
![image](https://user-images.githubusercontent.com/13508453/38963237-940563de-4379-11e8-9de0-f11786bebd3d.png)

**Comment by CapnKitten** [comment]
Fix is live.
