### ISSUE TITLE
Issue with list of voice/text rooms

### ISSUE THREAD

**Issue by dennythepilgrim** [CapnKitten/Material-Discord#31]
I have been having an issue where the list of voice and text rooms, where they start twitching, and then I cannot click on any of them, until I violently use the scroll wheel.

**Comment by CapnKitten** [comment]
I'm not able to reproduce it to find out why it's doing that. Are you able to make a gif of it?

**Comment by dennythepilgrim** [comment]
https://youtu.be/8he48r_Tnsk

**Comment by CapnKitten** [comment]
I'm gonna push an update live that'll remove the styling from the theme. Could you let me know if the issue still persists? Trying to narrow it down.
