### ISSUE TITLE
Busy Status

### ISSUE THREAD

**Issue by LeeWorezGaming** [CapnKitten/Material-Discord#32]
All of the other statuses seem to work (Online, Away and Invisible) apart from the Do Not Disturb feature. Apart from that, I love the provided animation.

**Comment by CapnKitten** [comment]
What's not working for you? The actual clicking of Do Not Disturb and it's not changing your status to that?

**Comment by LeeWorezGaming** [comment]
Pretty much. I go to change my status and it doesn't work, now that I'm doing it once again it is working. Must just have been one of those bugs. I can do another issue report if it occurs again.
