### ISSUE TITLE
Discord Server Banner

### ISSUE THREAD

**Issue by marcocusano** [CapnKitten/Material-Discord#33]
Hello,
I just want to report a new feature added by Discord 2 days ago, the **Server Banner**, for Verified DIscord Servers, allowed to upload this new Banner that will appear like that: https://media.discordapp.net/attachments/393843273652764674/553708013614268437/unknown.png.

Actually, on Material Design Theme it is bugged, showing just an empty space: https://imgur.com/qrmb2AF.

Regards,
Marco

**Comment by CapnKitten** [comment]
Didn't notice that, sorry. It'll be fixed with the next update, thanks.
