### ISSUE TITLE
Incompatibility with HorizontalServerlist

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#34]
Hello,

Could you please make your theme compatible with Gibbu's [HorizontalServerList](https://github.com/Gibbu/BetterDiscord-Themes/tree/master/HorizontalServerlist) micro-theme ?

Thanks !

**Comment by CapnKitten** [comment]
My theme is heavily customized compared to vanilla Discord, and with it being a theme instead of a plugin that adds some class names, I can't make it work without changing how the default server list on my theme looks. Sorry about this inconvenience.

**Comment by KaKi87** [comment]
That's weird because the Nox material theme is surprisingly compatible with the this one ^^
Or should I ask the other dev to make it compatible with yours ?

**Comment by CapnKitten** [comment]
It's compatible with Nox right now because the devs for that theme haven't updated it for the recent server list update in Discord.

**Comment by CapnKitten** [comment]
Alright, I made a separate theme file that'll make it look as intended. https://betterdiscord.net/ghdl?id=2786
