### ISSUE TITLE
"add server" button

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#35]
Hey,

The "add server" button is unthemed :

![2019-04-01 14_13_52-Settings](https://user-images.githubusercontent.com/21284089/55326661-94c90c00-5488-11e9-84df-cd9ff3b2948a.png)

Thanks !

**Comment by CapnKitten** [comment]
That's already fixed, just restart your Discord client.

**Comment by KaKi87** [comment]
Yep, thanks !
But, why did it required a restart ?
Usually, the ThemeRepo allows to update the theme without restarting 🤔

**Comment by CapnKitten** [comment]
I'm not entirely sure. I only get the ThemeRepo update prompt when I restart the client. But as long as it's fixed for you, all is well.
