### ISSUE TITLE
Cyrillic Font Support

### ISSUE THREAD

**Issue by LoLoAlexLoLo** [CapnKitten/Material-Discord#36]
Heya!
Google Sans font in this theme doesn't support cyrillic font
There is Google Sans (f.e [this](https://github.com/sahibjotsaggu/Google-Sans-Fonts/blob/master/GoogleSans-Regular.ttf)) that supports cyrillic characters and I hope you change it

Thanks

**Comment by CapnKitten** [comment]
It does support cryillic, as I got the files straight from Google. I just didn't have the proper font face code in the theme. I'll get it updated though, thanks.

**Comment by LoLoAlexLoLo** [comment]
yeah so you released an update with cyrillic font support but it doesnt work (yes i downloaded new version from github and restarted discord)
![image](https://user-images.githubusercontent.com/39464667/56192255-0b483b00-603f-11e9-9ddc-5d3f35a34e8c.png)

**Comment by CapnKitten** [comment]
I am fairly certain that it works now. Activity Feed doesn't seem to change even with the theme disabled, so that appears to be a Discord issue.

![q6GeB](https://user-images.githubusercontent.com/4013216/56230857-2456e900-604b-11e9-8257-e86439eaed20.png)

**Comment by LoLoAlexLoLo** [comment]
oh yeah, you right, now it is working
thanks again, now close this issue please (because i don't know how to do that :D)

**Comment by CapnKitten** [comment]
All good, glad I could get it fixed.
