### ISSUE TITLE
Not fully compatible with Redesign

### ISSUE THREAD

**Issue by chaNcharge** [CapnKitten/Material-Discord#37]
![image](https://user-images.githubusercontent.com/11594018/56623900-14ab4780-65eb-11e9-99bd-f41dafc501a0.png)

Not everything is themed and some parts are just broken or don't look right.

**Comment by Maximilian1271** [comment]
I second this issue. Might try to rework the css myself until there is an official fix for this

**Comment by CapnKitten** [comment]
I pushed an update live that fixed most of the issues so it doesn't look like shit, but I'm still working on it.

**Comment by chaNcharge** [comment]
Jump button is in the wrong place in the search results screen

![image](https://user-images.githubusercontent.com/11594018/56778271-51617500-678a-11e9-93cc-33eeac77e975.png)

**Comment by KaKi87** [comment]
Hey, could you also fix the styling for the [ServerFolders](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders) plugin that has been updated since the redesign ? Thanks !

**Comment by CapnKitten** [comment]
Both of those issues have been addressed in the latest update.

**Comment by chaNcharge** [comment]
I think everything looks good, but if you want to theme the buttons on mac so they don't look like this, `.macButtons-2MuSAC` should do
![image](https://user-images.githubusercontent.com/11594018/56868921-e09aa280-69ad-11e9-928f-a32dab90675f.png)

**Comment by CapnKitten** [comment]
I don't have a mac, but I'll see what I can do about it. As for the other issue, it'll be fixed in the next update I release.

**Comment by chaNcharge** [comment]
You could have it be the same color as the rest of the background. However if you think the color fits better as is, then feel free to leave it. 

![image](https://user-images.githubusercontent.com/11594018/56934285-52ebaf80-6aa0-11e9-84e7-9b3ae5061910.png)

**Comment by CapnKitten** [comment]
I'll make a macOS VM and get these issues fixed.

**Comment by CapnKitten** [comment]
The mac buttons + server folder issue are fixed in the update I just pushed live.

**Comment by KaKi87** [comment]
Is it normal that unread dot always appears on hover ?

**Comment by CapnKitten** [comment]
Yea, it's a quick fix from the recent Discord update until I find a way to make it like the old way.

**Comment by chaNcharge** [comment]
The RGB values are off a little bit on the mac and server folders menu. The server list is rgb(35, 35, 39) while the mac button and the top part of the server folders menu is rgb(32, 34, 37)
![image](https://user-images.githubusercontent.com/11594018/57050918-af330880-6c33-11e9-8f9f-293a02ac43f3.png)

**Comment by CapnKitten** [comment]
I'll have that fixed, plus the margin of the first server in a server folder and the mac buttons while in user/server settings.

**Comment by KaKi87** [comment]
There's also an incompatibility with the Citator plugin : the "close" button can't be clicked

![2019-05-04 22_46_45-#general-💬 - Discord](https://user-images.githubusercontent.com/21284089/57184642-a0ac5180-6ebe-11e9-992a-16e0ca9c00b7.png)

Thanks :)

**Comment by CapnKitten** [comment]
I'll get it fixed as soon as I can.
