### ISSUE TITLE
Plugin support - List plugins that look messed up here

### ISSUE THREAD

**Issue by CapnKitten** [CapnKitten/Material-Discord#39]
Because my theme is heavily customized, if a plugin doesn't function the same as with no theme, please list it here using the format below and I'll try to get it fixed as soon as possible.
&nbsp;
> - Plugin name
> - Developer name
> -  Git repo page (optional)
&nbsp;
> Images are optional

**Comment by KyzaGitHub** [comment]
* AntiGhostPing
 * Kyza
 * https://github.com/KyzaGitHub/Khub/tree/master/Plugins/AntiGhostPing

<img src="https://cdn.discordapp.com/attachments/580490876493627413/625700405921185792/2019-09-23_15-27-41.mp4" />
