### ISSUE TITLE
Elongated Spoiler tag.

### ISSUE THREAD

**Issue by FennisOT** [CapnKitten/Material-Discord#40]
Spoiler tag stretches out taking up the entire line as spoiler as non-spoiler text afterwards gets pushed down a line.

![Untitled](https://user-images.githubusercontent.com/14151917/59394803-1e317000-8d4f-11e9-923e-b7f62ad0a506.png)

**Comment by CapnKitten** [comment]
Changed with the latest update, sorry for the delay.
