### ISSUE TITLE
Incompatibility with MemberCount plugin

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#42]
Hey,

There's a glitch while using the [MemberCount](https://github.com/Arashiryuu/crap/tree/master/ToastIntegrated/MemberCount) plugin :

![2019-06-27 15_06_28-](https://user-images.githubusercontent.com/21284089/60277570-21eff580-98fe-11e9-8a39-226261b1e75f.png)

Thanks ! :)

**Comment by CapnKitten** [comment]
Not a glitch, just styled for vanilla Discord. Got it changed, and will put the update live soon.

**Comment by KaKi87** [comment]
It's slightly broken again :

![2019-07-26 21_45_56-#trigedasleng - Discord](https://user-images.githubusercontent.com/21284089/61977497-e163c480-afee-11e9-8fdf-f8d7fafc5e28.png)

Thanks !

**Comment by CapnKitten** [comment]
Issue has been fixed in v2.0.5.1
