### ISSUE TITLE
Animation for marking as read plays twice

### ISSUE THREAD

**Issue by tzAria** [CapnKitten/Material-Discord#43]
![2019-06-27_17-06-29](https://user-images.githubusercontent.com/14789279/60300876-fc62ec00-98fd-11e9-8d35-1a8174dc84c0.gif)

Clicking a server causes the little unread indicator to animate twice; once with a fade-out and once with the more complex animation.

**Comment by CapnKitten** [comment]
It's like that intentionally because of how the unread pill works now. Kind of a WIP until I figure out how I can make it a smooth transitionm

**Comment by CapnKitten** [comment]
Fixed this issue in the latest update.
