### ISSUE TITLE
Incompatibility with plugin "ImageToClipboard"

### ISSUE THREAD

**Issue by tzAria** [CapnKitten/Material-Discord#44]
ImageToClipboard adds another button to the image viewer, a "copy to clipboard" button. Normal functionality of this plugin is shown here:
![Discord_2019-06-30_15-56-27](https://user-images.githubusercontent.com/14789279/60401450-ab4a3680-9b4f-11e9-8237-2105b870dde5.png)
However, this theme moves the "Open original" button to a new button to the right, thus breaking the functionality of the plugin, seen here:
![Discord_2019-06-30_15-57-57](https://user-images.githubusercontent.com/14789279/60401465-d9c81180-9b4f-11e9-9ca6-b38cdea73487.png)

The plugin can be found here: https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ImageToClipboard

**Comment by CapnKitten** [comment]
Got it fixed, and will be put live soon.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the update is live.
