### ISSUE TITLE
Ability to edit the accent color with custom CSS?

### ISSUE THREAD

**Issue by royalPanic** [CapnKitten/Material-Discord#45]
I think it would be really awesome if we were able to manually set the accent color, such as with the  [Nox Theme](https://github.com/rauenzi/Nox). I really loved the Nox theme, but I wanted to check out some other themes and stumbled here. After using your theme, I believe I will end up sticking with it, but this minor feature from Nox seems like it would fit in really well here, but it's obviously not a deal breaker.

**Comment by CapnKitten** [comment]
You can already do this, although the variables are somewhat hidden to keep the theme file you download smaller. I'll make the variables easier to find.
