### ISSUE TITLE
v1.3.0 incompatible with "custom status" feature

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#47]
Title pretty much says it all. Theme has a small issue with the custom status feature and no longer renders status icons at all. 

Screenshot attached

![ss (2019-07-24 at 09 10 38)](https://user-images.githubusercontent.com/1573345/61821746-3f11d880-ae58-11e9-9a89-0d0dc3c75c51.png)

**Comment by CapnKitten** [comment]
v1.3 is really old. 2.0.4.1 is the current version with this issue, and many others, fixed.

**Comment by Maximilian1271** [comment]
Oh. Huge apologies then. Weird that it never got updated automatically

**Comment by EpiKaSteMa** [comment]
I am also having this issue with version 2.0.4.1.

**Comment by CapnKitten** [comment]
I just pushed v2.0.5 out with something that'll hopefully stop the caching with updates.
