### ISSUE TITLE
Server members with certain color roles flicker from bold to regular text

### ISSUE THREAD

**Issue by NickFlamel** [CapnKitten/Material-Discord#49]
I can confirm that this happens with #00005f and #ff0000, but I have not tested this issue with any other colors.

**Comment by NickFlamel** [comment]
![ezgif-4-d07035d99d8e](https://user-images.githubusercontent.com/20823203/62839979-10ba3880-bc61-11e9-9255-f8ac7787be64.gif)

**Comment by NickFlamel** [comment]
Kind of hard to see, but you can really see the red flicker

**Comment by CapnKitten** [comment]
The font weight isn't switching. For some reason, those two colors bug out due to the emoji and options button animations.

The code causing the issue is this:
`.buttonContainer-37UsAw > .popout-open,
.content-3dzVd8:hover .buttonContainer-37UsAw > * {
	opacity: 1;
	transform: translateX(0);
}`

I'll see what I can do about it.
