### ISSUE TITLE
Blurring user profiles.

### ISSUE THREAD

**Issue by FennisOT** [CapnKitten/Material-Discord#50]
When looking at someone's user profile through clicking on the user's icon it's normal (first image). When clicking a user's name on a member's list, the user profile is kinda blurred (second image).
Latest version. 1920 x 1080 resolution.

![no blur on clicking on user icon](https://user-images.githubusercontent.com/14151917/63614875-0c234780-c5b2-11e9-9564-e0fcd79e6604.png)
![blur on member list](https://user-images.githubusercontent.com/14151917/63614874-0c234780-c5b2-11e9-9cc2-84b6a9ddf885.png)

**Comment by CapnKitten** [comment]
It's like that due to the `translateX` value I used for the smoother animation. I changed it to the position of the default Discord theme, and will be fixed in the next update.
