### ISSUE TITLE
Wrong Z-Index of rpc app name

### ISSUE THREAD

**Issue by SpeedouTM** [CapnKitten/Material-Discord#51]
Just found an issue where the app name on the RPC status of an user goes behind the profile window. 

Look the image.
![Annotation 2019-09-06 195246](https://user-images.githubusercontent.com/34949863/64449328-eaf94580-d0df-11e9-9e0b-a393431eef0e.jpg)

**Comment by CapnKitten** [comment]
Got it fixed, and will be in the next update.
