### ISSUE TITLE
Update corrupted friends list rendering. 

### ISSUE THREAD

**Issue by wefalltomorrow** [CapnKitten/Material-Discord#54]
As seen here: https://i.imgur.com/IPDVNOP.png

**Comment by CapnKitten** [comment]
I'm not sure what caused that, but I don't think it's an issue with the theme.

**Comment by wefalltomorrow** [comment]
You're right, it was a conflict with this plugin: https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/TopRoleEverywhere

Is there any way to fix the conflict introduced in the latest update or is that out of the scope of this project?

**Comment by CapnKitten** [comment]
I can take a look at it.

**Comment by wefalltomorrow** [comment]
He introduced an update which seemed to fix it, thanks for the help!
