### ISSUE TITLE
Duration selection modal for custom status has incorrect z-index.

### ISSUE THREAD

**Issue by EpiKaSteMa** [CapnKitten/Material-Discord#56]

**Comment by CapnKitten** [comment]
I'm not sure what you mean. Can you take a screenshot and show me?

**Comment by EpiKaSteMa** [comment]
![image](https://user-images.githubusercontent.com/13809828/64745016-1ca15080-d4d4-11e9-872b-724a611383e8.png)

**Comment by EpiKaSteMa** [comment]
![image](https://user-images.githubusercontent.com/13809828/64745057-52463980-d4d4-11e9-924a-62f895154cbb.png)

**Comment by EpiKaSteMa** [comment]
The status selector issue appears to be a problem with my custom stylesheet I apologize.

**Comment by djsime1** [comment]
Issue appears in unmodified stylesheet as well.

**Comment by CapnKitten** [comment]
Issue is fixed, and will be live in the next update.
