### ISSUE TITLE
User volume slider // Message context menu // Message edit box

### ISSUE THREAD

**Issue by djsime1** [CapnKitten/Material-Discord#57]
1. The dot of the "User Volume" dot is below the slider (https://i.imgur.com/EILcAha.png)
2. The message context menu/reaction button moves inwards with each message (https://i.imgur.com/NiSD587.gif)
3. When editing a message, the side of the edit box decreases depending on the message's position. (https://i.imgur.com/m3MrN9Z.gif)

These are the current bugs I've found in 2.0.7.
If I find any more I'll add them to this thread.

**Comment by CapnKitten** [comment]
Fixed the first issue. As for the second and third, I was playing with the line height after the recent update and didn't encounter those problems. It'll be changed with the next update, so let me know if you still have this issue.

**Comment by djsime1** [comment]
Got it. Also, thank you for still maintaining this project. I really appreciate it. This is my go-to favorite theme.

**Comment by djsime1** [comment]
Update: Edit box fixed within latest update, however context menu still moves inward per each message.

**Comment by CapnKitten** [comment]
I increased the line height again, so hopefully it'll be fixed. I still haven't been able to reproduce this.

**Comment by djsime1** [comment]
After changing some Discord settings, I realized the cause was my chat font size being set to 14px, which is smaller than the default 16px. 16px font size works fine.
