### ISSUE TITLE
Chanel list

### ISSUE THREAD

**Issue by MrTheFunColas974** [CapnKitten/Material-Discord#58]
Hello is my favorit theme but i have one problem ! chanel list is very small for me you can is possible explain me where i can change format of this box please !
![unknown](https://user-images.githubusercontent.com/55397451/64965924-e76b7880-d8ae-11e9-8a7d-942074995b4b.png)

**Comment by CapnKitten** [comment]
It's the same width as vanilla Discord, but here's the element to change the width of it `.sidebar-2K8pFh`
