### ISSUE TITLE
Plugin Repo/Theme Repo/Repo Controls Issues

### ISSUE THREAD

**Issue by crazyian1000** [CapnKitten/Material-Discord#6]
So this isn't really discord itself, but I use a plugin repo and theme repo for finding new plugins and themes and also a repo controls for easy control over these repos (found in the mwittrien [github](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/)). Yet as you can tell from the images below, it gets cutoff/pushed close together and also the trashcan for deleting things is too close to the on/off buttons for the plugins/themes. If you could fix this it would be great, if not I understand since you can't really control these other plguins! Thanks so much, love the theme!

![capture3](https://user-images.githubusercontent.com/25258572/39717643-c23aa30e-51e8-11e8-8a62-94a66867e558.PNG)
![capture2](https://user-images.githubusercontent.com/25258572/39717645-c26f8bdc-51e8-11e8-956d-6de791e0b16d.PNG)
![capture](https://user-images.githubusercontent.com/25258572/39717644-c2537bea-51e8-11e8-95f2-4ce6baa2f2db.PNG)

To clarify the first two photos are the themerepo and the pluginrepo plugins and the issue with the trashcan is from the repocontrols plugin.

**Comment by CapnKitten** [comment]
Not a problem, I'll get it updated and should be out on the next update. I want to include the popular plugins in the theme, so thanks for bringing it to my attention.

**Comment by CapnKitten** [comment]
Update is live.

**Comment by crazyian1000** [comment]
Thanks so much for a fast fix! Only issue is plugins/themes that have a long description, the download/update gets cutoff, everything else looks perfectly fine, so whenever you have a chance to fix this one is fine! Thanks again so much, I wish more creator were like you! 

![capture](https://user-images.githubusercontent.com/25258572/39730510-e0f9493e-5216-11e8-8d04-de05f2e5c0e8.PNG)
![capture2](https://user-images.githubusercontent.com/25258572/39730582-5144fcf6-5217-11e8-93fe-a015548c5b52.PNG)
