### ISSUE TITLE
Search column width increasing on hover

### ISSUE THREAD

**Issue by KaKi87** [CapnKitten/Material-Discord#60]

**Comment by CapnKitten** [comment]
Could you be a bit more descriptive?

**Comment by KaKi87** [comment]
- Press Ctrl + F or click on the top right search bar
- Type something
- Press or click Enter
- The search column appears
- When the mouse hovers the search column, its width is larger than when it doesn't.
I don't know how to say it otherwise 😅 
Thanks

**Comment by CapnKitten** [comment]
Sorry for the delay, but found out why it was doing that. It'll be fixed in the next update, thank you.
