### ISSUE TITLE
Issue with DND icons, as well as certain others.

### ISSUE THREAD

**Issue by xSklzxDokkaebi** [CapnKitten/Material-Discord#62]
![image](https://user-images.githubusercontent.com/20905508/67446731-76d01e00-f609-11e9-874d-39f678b84ab7.png)
![image](https://user-images.githubusercontent.com/20905508/67446741-7df72c00-f609-11e9-98eb-3c00e5ee4033.png)
![image](https://user-images.githubusercontent.com/20905508/67446752-87809400-f609-11e9-8e63-5c2f05724a56.png)
Some icons appear without colour on the profile cards and others don't look right.

**Comment by CapnKitten** [comment]
That's not an issue. That's how they look by default without any themes. Status icons turn white when Discord detects anything running, such as a game or listening to Spotify.
