### ISSUE TITLE
Plugin and theme repo filtering not working.

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#63]
With the theme enabled, the sort by and order buttons of plugin/theme repo don't show anything if you click on them.

**Comment by CapnKitten** [comment]
It might be like that due to the `z-index` values that I was messing with for the recent nitro boosting update. It's working for me with some updates I haven't put live yet.

**Comment by CapnKitten** [comment]
Update is live. Please let me know if the issue still persists afterwards.

**Comment by ardittristan** [comment]
It works now!
