### ISSUE TITLE
Compat issues with newest version of "Old Title Bar"

### ISSUE THREAD

**Issue by NitroxydeX** [CapnKitten/Material-Discord#64]
Plugin dev told me it seems to be a problem with the theme so I'm reporting this here

![image](https://user-images.githubusercontent.com/9305576/68253025-30c28380-0027-11ea-9fae-a7fa98d380fa.png)

the empty space besides the reload button should contain the window interactions

https://github.com/mwittrien/BetterDiscordAddons/issues/316

**Comment by CapnKitten** [comment]
Fixed and will be put live soon.
