### ISSUE TITLE
Causes issue with plugin "TopRoleEverywhere" (mwittrien)

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#65]
v2.0.9.1 causes an issue with the plugin [TopRoleEverywhere](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/TopRoleEverywhere).

Vanilla theme:
![ss (2019-11-12 at 12 47 01)](https://user-images.githubusercontent.com/1573345/68669833-cb512400-054b-11ea-952f-1cf7a27f7192.png)

With Material-Discord:
![ss (2019-11-12 at 12 47 24)](https://user-images.githubusercontent.com/1573345/68669847-d5732280-054b-11ea-9bc5-79e499ff46a3.png)

<hr>

Statement of mwittrien:
![ss (2019-11-12 at 12 56 57)](https://user-images.githubusercontent.com/1573345/68669899-f20f5a80-054b-11ea-8cc6-01ec6ee8a950.png)

**Comment by CapnKitten** [comment]
Issue has been fixed with v2.0.9.2.
