### ISSUE TITLE
v2.0.9.4 Emoji picker icon not in line with other icons in message box

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#67]
In v2.0.9.4, the emoji picker icon floats above the gif picker and nitro btn

![ss (2019-12-11 at 06 46 38)](https://user-images.githubusercontent.com/1573345/70595947-f4b1ae00-1be4-11ea-844e-5931bf73c2ad.png)

**Comment by Maximilian1271** [comment]
I am not an expert with css but to me it looks like the `max-height` property in the `.emojiButton-3uL3Aw` class causes this. However this is from discords own stylesheet so i do not know what exactly the cause of the problem is here.

**Comment by CapnKitten** [comment]
Just noticed this as well, and is fixed with v2.0.9.5.
