### ISSUE TITLE
[Bug] Character counter not showing up

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#68]
DevilBro's character counter plugin does not show the character counter with the theme enabled.

**Comment by CapnKitten** [comment]
I'm not sure which version of Discord you're using, but that plugin isn't working for me with no themes or plugins enabled.

**Comment by ardittristan** [comment]
BD version
![image](https://user-images.githubusercontent.com/42787508/72855778-e44b2380-3cb8-11ea-8209-73191bbc1493.png)
Plugin version
![image](https://user-images.githubusercontent.com/42787508/72855791-ef9e4f00-3cb8-11ea-9053-ba5c9f0d64ac.png)
Without theme
![image](https://user-images.githubusercontent.com/42787508/72855903-57ed3080-3cb9-11ea-95af-4125b3d69e85.png)
With theme
![image](https://user-images.githubusercontent.com/42787508/72855994-9387fa80-3cb9-11ea-9f90-1f217776e3d1.png)


make sure you get CharCounter by DevilBro and not Character Counter by Square
[https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CharCounter](url)

**Comment by CapnKitten** [comment]
Gotcha. Got it fixed and an update will go live soon, thanks.
