### ISSUE TITLE
[Bug] Text does not go to a new line in very long strings

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#69]
When the discord windows is made thin (on my 9:16 monitor for example where I fullscreen discord) the text can scroll off the screen with the theme enabled

With
<img src="https://user-images.githubusercontent.com/42787508/72857285-7f45fc80-3cbd-11ea-9525-a480ba3a026f.png" alt="With" width="500" height="200">
Without
<img src="https://user-images.githubusercontent.com/42787508/72857303-8bca5500-3cbd-11ea-90ee-f9930dc2d4ad.png" alt="Without" width="500" height="200">
With
<img src="https://user-images.githubusercontent.com/42787508/72857339-a3a1d900-3cbd-11ea-9d8a-d8c5d5043af8.png" alt="With" width="200" height="700">
Without
<img src="https://user-images.githubusercontent.com/42787508/72857365-b1eff500-3cbd-11ea-9464-ff7db673578b.png" alt="Without" width="200" height="700">

**Comment by ardittristan** [comment]
The scrolloff in code blocks only happens if there's no space for more letters than the screen is wide

**Comment by CapnKitten** [comment]
I'm not able to get Discord small enough to reproduce this issue.

**Comment by ardittristan** [comment]
when I fullscreen it it is at 1080 pixels wide and 1920 pixels long.
My discord can go as small in width as 942 pixels wide (without any plugin, with the plugin that removes the restriction it can be any size I want (RemoveMinimumSize by Zerebos), but it happens to me at a size that's doable without any plugins (and with the plugin disabled).

here's the string I'm using rn as test: `bind "KP_INS" "ulx luarun local tr = Entity(2):GetEyeTrace() if (IsValid(tr.Entity))then Entity(2):PrintMessage(HUD_PRINTCONSOLE,os.date([[%H:%M:%S]])..'Position:'..tostring(tr.Entity:GetPos())..'\t'..tostring(tr.Entity:GetAngles()))end"`

and here's the role name that was too long `raxxin is the nicest and best looking member in this server`

**Comment by CapnKitten** [comment]
Got it fixed and is in v2.1.4.1
