### ISSUE TITLE
chat area button box shadow

### ISSUE THREAD

**Issue by muscularcandy67** [CapnKitten/Material-Discord#7]
Can you pls fix the box shadow seen on the attach icon and eventually other icons? is really weird to see and you cant see it unless you don't have something shareable running
no spotify
![image](https://user-images.githubusercontent.com/12277635/41057850-81111a8c-69c8-11e8-8ee2-a8ec36fb39b9.png)
spotify
![image](https://user-images.githubusercontent.com/12277635/41057864-885948c8-69c8-11e8-80f7-59363e9e9986.png)

**Comment by CapnKitten** [comment]
It was added in the latest Discord update. I'll get it fixed and put live as soon as possible.
