### ISSUE TITLE
Messages Rendering Weirdly

### ISSUE THREAD

**Issue by PhantomIsHere** [CapnKitten/Material-Discord#71]
Discord recently changed the "box" and added this new fast reaction thing, the messages now look a little bit weird.
I would appreciate if you could make it so that it's like before again ;)

Thanks in advance

**Comment by kkrypt0nn** [comment]
Same for when you send or receive audio files

**Comment by CapnKitten** [comment]
Got all of those issues fixed with v2.1.7, thanks.
