### ISSUE TITLE
Polish characters have different font

### ISSUE THREAD

**Issue by Lubieerror** [CapnKitten/Material-Discord#73]
You can use Polish characters (ąćęłńóśźż) but the font is clearly different. 
![HAVE A](https://user-images.githubusercontent.com/11427815/74156755-47283e80-4c17-11ea-961a-ebf2bf0fc4c3.png)

Monospaced is ok:
![FANTASTIC](https://user-images.githubusercontent.com/11427815/74156818-6757fd80-4c17-11ea-90df-08bd5e80cb88.png)

It could be just outdated font. I tested it and it looks that some versions of this contains missing characters.
![DAY](https://user-images.githubusercontent.com/11427815/74226131-4ac1d100-4cbc-11ea-9973-689d280a067e.png)

It isn't critical bug so no need to worry. Just nice thing to have. 
Anyway fantastic job. I'm really surprised with speed you're making updates. Really big thank you for all that effort!

**Comment by CapnKitten** [comment]
Sorry about that, didn't realize that it wasn't using the correct font for non-english languages. I'll get that fixed as soon as possible.

**Comment by CapnKitten** [comment]
Update is live, and the characters are using the same font in v2.1.8.
