### ISSUE TITLE
Problem with BetterFormattingRedux with 'Text' as icon

### ISSUE THREAD

**Issue by holysnipz** [CapnKitten/Material-Discord#75]
when using Text as BFRedux's icon type:
![image](https://user-images.githubusercontent.com/9103583/75104290-0a5a3f80-563a-11ea-8513-9f85a71eb6f0.png)

with [`width: 27px`](https://github.com/CapnKitten/BetterDiscord/blob/master/Material-Discord/css/source.css#L15185) removed:
![image](https://user-images.githubusercontent.com/9103583/75104881-cd457b80-5640-11ea-8a65-d41b01b0c0e1.png)

But since [`:has()` is not a thing yet](https://caniuse.com/#feat=css-has), not sure if there's better way than removing the [`width: 27px` from `.bf-toolbar .format`](https://github.com/CapnKitten/BetterDiscord/blob/master/Material-Discord/css/source.css#L15185) *~~or me just start using image as icon instead~~*

**Comment by CapnKitten** [comment]
This is fixed in the update I just put live, thanks.
