### ISSUE TITLE
Chat Bubble Header Arrow Issue.

### ISSUE THREAD

**Issue by SnowyHuskybutt** [CapnKitten/Material-Discord#79]
Hey there, I noticed recently that the Chat Bubble arrow is directly tied to the header, and from a change recently, something I use alongside your theme no longer functions correctly at all I have a donator tag from a discord named Black Box and the tags used to work fine with your theme, but a recent change you pushed I think broke them entirely for use on Material.

I'd like to ask if I could maybe contact you via discord to tell you about the issue directly as I found a workaround solution to have the arrow not directly linked to the headers.

**Comment by CapnKitten** [comment]
Sure, my Discord tag is in most of the screenshots.

**Comment by SnowyHuskybutt** [comment]
Appreciate it, I sent a request over.

I'm Nereus if there's any confusion!
