### ISSUE TITLE
can't attach custom CSS editor

### ISSUE THREAD

**Issue by Mara-Li** [CapnKitten/Material-Discord#81]
![image](https://user-images.githubusercontent.com/30244939/77197131-eb3db900-6ae4-11ea-8430-dca4e4afc9d9.png)

No button + click on attach doesn't nothing :<. The only way for me to quit the thing is to CTRL+R discord.

**Comment by CapnKitten** [comment]
Fixed the attach button and the buttons below the text editor, but the editor itself (without any themes or plugins) bugs out when you attach the editor back. The fix will be in the next update, thanks.
