### ISSUE TITLE
Is there a way to change the search and add server icons to black when the accent color is light?

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#83]
![image](https://user-images.githubusercontent.com/24306400/77861612-f16a1e80-71e3-11ea-8035-67c8d79f8b6c.png)

**Comment by CapnKitten** [comment]
Just updated the theme to v.2.2.1 to include an `accent-text-color` variable. Update the theme and use the variable in custom CSS to change it.

**Comment by Jnss98b** [comment]
@CapnKitten  Could you link these text and icon to the color variable too?

![image](https://user-images.githubusercontent.com/24306400/78414092-7c825480-75e8-11ea-828d-32c5298b8cbd.png)
![image](https://user-images.githubusercontent.com/24306400/78414103-8b690700-75e8-11ea-869d-a8b466cb6ce6.png)

**Comment by CapnKitten** [comment]
Sure thing.

**Comment by Jnss98b** [comment]
Alright, thanks!

**Comment by Jnss98b** [comment]
@CapnKitten I just found two more icons. The search icon in the friend list and the default server icons

![image](https://user-images.githubusercontent.com/24306400/78457013-4808aa00-7675-11ea-83c2-c21414d984d4.png)
![image](https://user-images.githubusercontent.com/24306400/78457039-6b335980-7675-11ea-958a-0b3506a21945.png)

**Comment by Jnss98b** [comment]
And all of these accented elements in the public servers finder have hardcoded white texts that should be linked too
![image](https://user-images.githubusercontent.com/24306400/78457101-e1d05700-7675-11ea-8e91-5bdca429f726.png)

**Comment by CapnKitten** [comment]
Won't be able to change the search icon based on a variable because it's using `background-image` to show it.

**Comment by Jnss98b** [comment]
I just found the scroll to the bottom button and the load more messages notif have hardcoded colors too @CapnKitten 
![image](https://user-images.githubusercontent.com/24306400/79011483-22c2e280-7b32-11ea-8c65-f91cc471af95.png)
![image](https://user-images.githubusercontent.com/24306400/79011499-2eaea480-7b32-11ea-8be2-81640be5434f.png)

**Comment by CapnKitten** [comment]
The arrow button has the same "issue" as the search icon above. Because it isn't there on vanilla Discord, I have to use a `background-image` using an SVG icon. The load more messages button can be changed though.

**Comment by Jnss98b** [comment]
Wait, I thought you can change the color of a vector? Is it because css doesn't offer that ability?

**Comment by CapnKitten** [comment]
The way I handle using SVG icons in CSS is by encoding it to base64 like so:
![aY7Ne](https://user-images.githubusercontent.com/4013216/79033749-cafe9880-7b7e-11ea-81be-0e05fef74469.png)

**Comment by Jnss98b** [comment]
Sorry I don't know much about css but this might help

https://stackoverflow.com/questions/22252472/how-to-change-the-color-of-an-svg-element

![Screenshot_20200411-021542](https://user-images.githubusercontent.com/24306400/79036909-de1f6180-7b9a-11ea-8cb1-f903cfd67c4b.png)

**Comment by CapnKitten** [comment]
If the svg element was hardcoded into the HTML, I could change the fill color with no issue, but in order for me to add it in it has to be done via `background` or `background-image`. Which essentially makes it an image, so no using any svg properties.

I'm able to straight up use the svg tag in the background-image url, but when trying to change the fill color, the hex color code with `#` messes it up and doesn't allow the background-image to show up at all.

```
background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M24 24H0V0h24v24z" fill="none" opacity=".87"/><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6-1.41-1.41z"/></svg>');
```

**Comment by Jnss98b** [comment]
Oh that's fine no worries

**Comment by Jnss98b** [comment]
@CapnKitten  Sorry I keep finding them😅

![image](https://user-images.githubusercontent.com/24306400/79122299-589bdd00-7d65-11ea-87bb-5617cb4fb3ac.png)

**Comment by CapnKitten** [comment]
Sorry for the massive delay. I'm not sure where the bottom image is, but the checkboxes are changed to work with it.

Also, I changed how the button hover and active colors work.

Instead of using `--accent-color-hover` and `--accent-color-active`, the colors will be one color using the `--accent-button-action` variable and the opacity will change for the hover and active states using `--accent-button-action-hover` and `--accent-button-action-active`.

Same goes for the alert buttons; just replace `accent` with `alert` and it'll change the buttons that are red by default in the theme.

**Comment by Jnss98b** [comment]
Red buttons as in this one?
![image](https://user-images.githubusercontent.com/24306400/81426273-f8f7de00-9126-11ea-8958-f088e4ddb80e.png)

**Comment by CapnKitten** [comment]
Forgot about that one. It'll be included.
