### ISSUE TITLE
Spotify's "Play song" button is all white, unreadable font

### ISSUE THREAD

**Issue by aulialuthfi99** [CapnKitten/Material-Discord#84]
Hello
I just found your theme, it's cool. But, I've found a bit of a problem with your theme. When someone listens on Spotify, it'll show up in his discord and there's a button for "Play that current song" and "Listen along", but the "Play that current song" is all white
![image](https://user-images.githubusercontent.com/45804108/77943698-db458680-72e7-11ea-9e09-b9867ec58561.png)
Tried changing line 3241 from `--accent-color` to `--spotify-color`, it works. Dunno if that's gonna break something

**Comment by CapnKitten** [comment]
Accidentally included that button when I was changing all of the button text colors. It's fixed and will be put live soon, thanks.
