### ISSUE TITLE
[Material-Discord] HTML5 Videoplayer, misaligned buttons (V. 2.2.3.1)

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#86]
Hello :)

I am not entirely sure that Material Discord is to blame here, however, I have tested this with all plugins disabled/removed and I have compared it to the vanilla theme (in which it is working properly).

Using version 2.2.3.1, all HTML5 <video> elements appear to have the play/pause button floating above the baseline of all the other buttons.

A screenshot that should help with illustrating the issue:

![ss (2020-04-05 at 03 45 01)](https://user-images.githubusercontent.com/1573345/78464983-8e4f1f00-76f0-11ea-964f-79f27bbd1ab5.png)

**Comment by CapnKitten** [comment]
Every so often, a Discord update likes to change things like that for no reason at all. I'll get it fixed as soon as I can, thanks.

**Comment by Maximilian1271** [comment]
Haha yeah, discord doing discord things. What else is new xD
