### ISSUE TITLE
[Bug] Video icon not showing

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#87]
with discord having their better version of videochat/screensharing it now shows a video camera when someone has their camera on in a server channel:
![image](https://user-images.githubusercontent.com/42787508/79003447-ee135300-7b52-11ea-83c2-b7764f1e7a78.png)
but with the skin on the camera is hidden:
![image](https://user-images.githubusercontent.com/42787508/79003465-f79cbb00-7b52-11ea-8b6a-b842ffe96aa7.png)

**Comment by CapnKitten** [comment]
Wasn't aware of that icon, will get it fixed as soon as possible, thanks.

**Comment by CapnKitten** [comment]
This is fixed in v2.2.3.3.
