### ISSUE TITLE
stop watching stream with new ui not working

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#88]
with the experimental video ui on:
![image](https://user-images.githubusercontent.com/42787508/79083529-1d7eb700-7d2f-11ea-8354-30779991fe0d.png)
the stop watching stream button only shows text when it's popped out.

how it's supposed to look:
![image](https://user-images.githubusercontent.com/42787508/79083545-371ffe80-7d2f-11ea-8365-af0fded802a0.png)

how it looks when not popped out:
![image](https://user-images.githubusercontent.com/42787508/79083558-443ced80-7d2f-11ea-9cce-497766f84cfe.png)

**Comment by CapnKitten** [comment]
I don't usually mess with experimental features because they don't always make their way into a stable Discord release, but I suppose I can fix this one issue this time. I'm the same way when it comes to Discord canary as well.

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/79173827-03111000-7df9-11ea-847d-b415f67f1006.png)
it has been made official for 5% of the userbase now, I don't know if you still consider that experimental or not since it's on discord stable

**Comment by CapnKitten** [comment]
I have it fixed anyway, so it's all good. Just gotta put it live.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the fix is live with v2.2.4
