### ISSUE TITLE
Icon misplacement on lower than default chat scaling.

### ISSUE THREAD

**Issue by FennisOT** [CapnKitten/Material-Discord#89]
Looking at the pinned messages tab, when the chat font scaling is smaller than the default 16px, the user icon moves over.
![Untitled](https://user-images.githubusercontent.com/14151917/79153659-35d8eb00-7d9c-11ea-8fc7-151f759e8fcf.png)

Side-note:  The Create DM highlight is weird again for me.

**Comment by CapnKitten** [comment]
Didn't think about pinned messages when I dealt with the chat font scaling issue before. I'll get it fixed as soon as I can, but it might be delayed a bit so I can put more into an update. The create DM ripple will also be fixed in the same update. Thanks.

**Comment by CapnKitten** [comment]
Sorry for the delay, but the fix is live with v2.2.4
