### ISSUE TITLE
Message triangles look weird if the GUI scale is less than 100%

### ISSUE THREAD

**Issue by coltondrg** [CapnKitten/Material-Discord#9]
![image](https://user-images.githubusercontent.com/5587661/41503640-055e583e-7196-11e8-885f-6d6da056314f.png)

The little triangles between the message box and user avatar don't render correctly if the GUI scale is lower than 100%. I was going to just disable them but I can't find the CSS that creates them so I can't figure out what the CSS I need to use to get rid of them is.

**Comment by CapnKitten** [comment]
The code you're looking for is:
`.message-group .comment .message.first:before`

**Comment by coltondrg** [comment]
That worked, thank you very much. One last thing, after setting the above to `display:none;`, the upper left corner of the message boxes are not rounded like the other corners. How would I turn that on?

**Comment by CapnKitten** [comment]
Find this, and delete the border-top-left-radius
`.message-group .comment {
	padding: 12px 8px;
	background: var(--message-color);
	border-top-left-radius: 0 !important;
	transition: 200ms ease all !important;
}`

**Comment by coltondrg** [comment]
Ah, thanks, I actually found it on my own just as you posted that. I just put this in the custom stylesheet so I wouldn't have to edit the theme's files.
```
.message-group .comment .message.first:before {
    display:none;
}
.message-group .comment {
    border-top-left-radius: var(--border-radius) !important;
}
```

**Comment by CapnKitten** [comment]
Awesome, glad I could help.
