### ISSUE TITLE
Animated Icons cause high cpu usage

### ISSUE THREAD

**Issue by ardittristan** [CapnKitten/Material-Discord#90]
The animated icons on the server list in this theme use a lot of cpu for me, this is with my server list enabled: 
![image](https://user-images.githubusercontent.com/42787508/80507243-f0f5ac80-8976-11ea-9244-62a5073d4263.png)
This is with the server list hidden:
![image](https://user-images.githubusercontent.com/42787508/80507309-04a11300-8977-11ea-81fa-5748f2109615.png)
And this is with the theme disabled and server list shown:
![image](https://user-images.githubusercontent.com/42787508/80507411-1edaf100-8977-11ea-9948-974cf9d522ea.png)

Would it be possible to add an option to disable the animations or look into their performance.

**Comment by CapnKitten** [comment]
Listing the CPU usage without saying what CPU you have is kind of redundant. With that said, the animation is just a box-shadow and not much can be done about the performance hit you're experiencing. Add this to your custom CSS to remove the animation:
```
.iconBadge-2NuvG9 {
    animation: none !important;
}
```

**Comment by ardittristan** [comment]
thank you for the info, it worked!

(as a side note, sorry, my cpu is a i5-8600k overclocked to 5GHz)

**Comment by CapnKitten** [comment]
Interesting that it would cause such a high cpu usage with an i5 8600k clocked at 5ghz. I saw around 3-4% usage with the animation enabled on my Ryzen 5 2600, and your has better IPC. With the animation off, it dropped to around 2%.

**Comment by ardittristan** [comment]
I did figure out part of my issue, apparently hardware acceleration was turned off. even though with hw accell on it still increases cpu usage by about 10% for me

**Comment by itsTyrion** [comment]
This is still an issue for me. Ryzen 3100 @ 4.1GHz. Discord uses around 7-9% as soon as the animation is played one 1 guild, more with 2+.
Disabling the theme/animation (`.iconBadge-32fMme { animation: none !important; }`) drops it back to 0-2%.
![image](https://user-images.githubusercontent.com/17730120/161404755-2ed7d722-7b0d-40e9-8682-36f318978a3a.png)
![image](https://user-images.githubusercontent.com/17730120/161404802-28ad8f02-fd2a-48c0-a54e-34821946d617.png)

Do you mind adding a setting for this? On older/weaker CPUs, I can see this being an issue.

**Comment by CapnKitten** [comment]
I'll remove the animation.
