### ISSUE TITLE
Deafen/Mute show wrong pictogram when in call

### ISSUE THREAD

**Issue by Maximilian1271** [CapnKitten/Material-Discord#91]
Hello again :)

I couldn't help but notice that in the current (v. 2.2.6) version, when choosing either mute or deafen, an incorrect pictogram or icon is shown in the participants section during an ongoing phone call. 

To illustrate what I mean:

Standard behaviour in the vanilla theme:
The correct icon is shown in the participants screen when using the mute/deafen function (marked with a red circle)
![MaterialDiscordBug1](https://user-images.githubusercontent.com/1573345/80633848-bc0e5600-8a59-11ea-8d14-a5eedcdaad5d.png)

Broken behaviour in the current version of the theme:
An incorrect icon is shown. It could be that i am mistaken and this is indeed the intended icon, however, if so, i think this iconography is very confusing:
![MaterialDiscordBug3](https://user-images.githubusercontent.com/1573345/80634072-20311a00-8a5a-11ea-89c1-ed8e6784a7e6.png)

Kind regards :)

**Comment by CapnKitten** [comment]
Got it fixed, and will be put live soon, thanks.
