### ISSUE TITLE
Implementing a light theme

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#93]
Would it be possible to make this material theme light mode compatible?

**Comment by CapnKitten** [comment]
Possible, yes. Likely to happen, probably not because I'd have to rewrite a good bit of the code.

**Comment by Dynakarp** [comment]
I'd love to see this happen! This is a great theme, and I'd love to see it have light mode support.

**Comment by CapnKitten** [comment]
Implemented with v3.0.0.
