### ISSUE TITLE
Emote alt text/label

### ISSUE THREAD

**Issue by Aeswere** [CapnKitten/Material-Discord#94]
Not entirely sure this is the place where this would belong, but I'm trying to make the text of a emote when you hover over it larger as it's very small on my second monitor and I don't know how to do it. I know a little bit of html/css basics but I doubt i'd be able to figure this out.

**Comment by CapnKitten** [comment]
The size of the tooltips is universal. Meaning, if you change the size of it for one thing, it'll change the size of it for everything else that has a tooltip.

**Comment by Aeswere** [comment]
I did just look for more tooltips with that note and I found that the ones I could easily find (mainly hovering over servers) is tiny, not sure if that has to do with window size or any other factors, but maybe it could be mentioned in any customization files?

**Comment by CapnKitten** [comment]
All tooltips are the same size (font size, padding, etc.), but they grow with the amount of text in them. The only way to make them bigger is to adjust the font size and padding, but that would change every tooltip in Discord. If you want larger tooltip, you can use the element I mentioned above and play around with the font size and padding.

Window size wouldn't change the size of the tooltips, but your scale size in Windows 10 would effect the entire Discord app and everything else in Windows.
