### ISSUE TITLE
Tiny "Edit Channel" and "Invite to Server" icons only in some servers but not in most

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Material-Discord#98]
Tiny icons bug
![image](https://user-images.githubusercontent.com/24306400/85215751-ee964a00-b34a-11ea-90c0-3d7194a87381.png)
![image](https://user-images.githubusercontent.com/24306400/85215801-68c6ce80-b34b-11ea-863c-30d9891f0c8e.png)

When it displays correctly
![image](https://user-images.githubusercontent.com/24306400/85215767-08d02800-b34b-11ea-91ea-beac0f82556b.png)
![image](https://user-images.githubusercontent.com/24306400/85215811-7bd99e80-b34b-11ea-9701-731d8fa212cc.png)

**Comment by CapnKitten** [comment]
I was able to find the one for "Invite to Server", but not one for the wrong "Edit Channel" icon. Although, I think I'm able to fix it without experiencing it for myself. If not, just let me know, thanks.

This fix will also be with the previous issue you opened.

**Comment by Jnss98b** [comment]
The "Create Invite" icon fix looks thinner than the normal one

![image](https://user-images.githubusercontent.com/24306400/85240454-3fb74400-b406-11ea-805a-6c6b634418d8.png)
![image](https://user-images.githubusercontent.com/24306400/85240462-46de5200-b406-11ea-81ca-e6b98317d60e.png)

Also the "Edit Channel" icon is still tiny for me

**Comment by CapnKitten** [comment]
The top one next to play-now is how it's supposed to look. When replacing the "Create invite" icons, I didn't realize that there were multiple svg paths, so it made it appear thicker than it's supposed to look.

As for the "Edit Channel" icon, I haven't seen it yet. Would you be able to take a screenshot of the dev console with the icon selected?

Something like this:
![h7Nh3](https://user-images.githubusercontent.com/4013216/85242136-2913eb80-b40c-11ea-8e13-1f35b40c37a4.png)

**Comment by Jnss98b** [comment]
![image](https://user-images.githubusercontent.com/24306400/85328728-3a5a0800-b49f-11ea-8fed-d7b452cf46a2.png)

This is it I think

**Comment by CapnKitten** [comment]
Perfect. I'll get the fix live as soon as possible, thanks.
