### ISSUE TITLE
Volume Slider, Emoji Panel Issues + Third-Party ServerSearch Plugin Compatibility and more

### ISSUE THREAD

**Issue by microtechton** [CapnKitten/Material-Discord#99]
Hey there,
Thank you for this beautiful theme and continuing development!
I have noticed some issues which tamper with the basic functionality of Discord as well as third-party plugins.

I am currently running the following:
```
Material_Discord v2.3
Stable 62028 (89ee84d)
BBD 0.3.4 (32e6212)
Host 0.0.306
Injector 0.4.1
Windows 10 64-Bit (10.0.19041)
```  
---
## Volume Slider During Screen Share
When in a voice chat with another individual who is sharing their screen, it is challenging to set the max volume using the volume slider.

![Volume Slider](https://user-images.githubusercontent.com/48565151/85350737-ed425a00-b4cf-11ea-87de-9cd7d6102396.gif )

As you can see, after dragging the slider a little higher than the max, immediately dismisses the slider and the volume becomes muted. As a result, this forces the user to be precise with the volume control to get their desired outcome.  
***
 ## Automatic Closure of Emoji Panel
With the latest update, Discord has introduced a new GIF and Emoji Picker. While this may be great news, it is difficult to dismiss this pop-up with the current version of the theme.  

![Emoji_Panel](https://user-images.githubusercontent.com/48565151/85352426-eddcef80-b4d3-11ea-8a84-5ecd50297c0f.gif)  

In this case, clicking on the "Got It" button dismisses the Gif + Emoji Panel entirely and brings back that pop-up open opening the panel again. I am assuming that the theme thinks I am pressing in an open space and not pressing a button, so it reopens that message again.  
***
## Blinding of Accents
Currently, I have the following code snippet in my custom CSS for changing my colour accents:
```
:root {
    --accent-color: #FD905D !important;
    --accent-button-action: #FD905D !important;
    --accent-rgb: #FD905D !important;
    --accent-text-color: #1B1B21 !important;
    --alert-color: #FD905D !important;
    --alert-text-color: #1B1B21 !important;
    --audio-flash: #FD905D !important;
    --message-color: #202225 !important;
}
```
Because this is a light colour, role calls, channel, and user mentions make the message difficult to read due to the bright and light colours. The following are multiple examples of this scenario:  

**Mention:**  

![image](https://user-images.githubusercontent.com/48565151/85353740-f97de580-b4d6-11ea-8158-1da4dbd6b2e2.png)  

![image](https://user-images.githubusercontent.com/48565151/85354047-abb5ad00-b4d7-11ea-8073-51a77f30d68a.png)  

**Channel Mention:**  

![image](https://user-images.githubusercontent.com/48565151/85354250-241c6e00-b4d8-11ea-8570-ced764f6d895.png)  

As you can see, the text becomes difficult to read and it would be of great benefit if you could find an alternative way to still use accents in a less blinding manner such as retaining the text in accent colours and decreasing the brightness of the background.  

The following is an example from [Nox Theme by Zerebos](https://github.com/rauenzi/Nox).  

![image](https://user-images.githubusercontent.com/48565151/85354938-9fcaea80-b4d9-11ea-88c9-3f648365abd6.png)  

![image](https://user-images.githubusercontent.com/48565151/85355137-f20c0b80-b4d9-11ea-9af2-8ce987dbb07d.png)  
***
##  Search Button
The search button does not seem to conform to the Material Design guidelines as there are no click animations.  Also, there appears to be a slight collision or overlap with the scroll bar.

![image](https://user-images.githubusercontent.com/48565151/85355622-0a305a80-b4db-11ea-8f42-ac563d0f34bf.png)

The following could be an example of how this could be solved:  

![1JQ9YiQsiG](https://user-images.githubusercontent.com/48565151/85356086-18cb4180-b4dc-11ea-811e-794354878cf1.gif)  
***
## Server Search (Third Party Plug-in) issue
There seems to be a bounding issue for the plugin [ServerSearch v0.1.3 by Zerebos](https://betterdiscord.net/ghdl/?id=1580) when enabled on this theme.  

![image](https://user-images.githubusercontent.com/48565151/85356432-eec64f00-b4dc-11ea-856f-5002447e6700.png)

It would be wonderful if this compatibility issue is resolved in a future update.  
***
## Suggestions
Would it be possible to implement a toggle to enable or disable the notification icon on the server avatars for a clean look?

Also, it would be visually pleasing if the notification icons also followed the accents mentioned in custom CSS.  

![image](https://user-images.githubusercontent.com/48565151/85356866-11a53300-b4de-11ea-9547-4677d52752b3.png)
***  
Once again, thank you so much for the development of this theme. It is undoubtedly one of the most attractive and stable themes apart of the BetterDiscord Themes Library, and I wait for the update for this theme!

**Comment by CapnKitten** [comment]
Bug that will be fixed in the next update:
- Volume slider.
- Mentions background color to make the text more visible with lighter accent colors.
- Server Search plugin fixed.
- Search button ripple effect added.
- Search button positioning. Although, at that point, you're really nitpicking for a Discord theme.

I currently can't get the emoji tooltip to pop up, so I'm unable to view the code and fix it, sorry.

---

For the suggestions:
- Having a toggle is not possible with CSS alone, so the only way of removing the server notification dot is to do so in custom CSS.
- For the color of the notifications, there's the `--notification-color` variable that handles the color for it. Most of the variables are listed [here](https://github.com/CapnKitten/Material-Discord#variables).

**Comment by microtechton** [comment]
Thank you so much for taking in my suggestions and bugs into consideration. I apologise for the nit-pickiness as this theme was wonderfully curated and I wished for it to look perfect.  

Anyway, I have found a way to close that Emoji Panel pop-up message. Basically, resizing the Emoji Panel automatically dismisses this pop-up and it never returns again.   

Once again, thank you so much!

**Comment by Jnss98b** [comment]
I found a workaround for the emoji panel issue. You could temporarily disable the theme to dismiss the onboarding message and re-enable the theme afterward
